// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HealthCheck struct {
	ID        int32
	CheckedAt pgtype.Timestamptz
}

type Session struct {
	ID                  pgtype.UUID
	SessionTokenHash    []byte
	SessionType         string
	PhotobookID         pgtype.UUID
	TokenVersionAtIssue int32
	ExpiresAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	LastUsedAt          pgtype.Timestamptz
	RevokedAt           pgtype.Timestamptz
}
