// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (
    id,
    session_token_hash,
    session_type,
    photobook_id,
    token_version_at_issue,
    expires_at,
    created_at,
    last_used_at,
    revoked_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NULL, NULL
)
`

type CreateSessionParams struct {
	ID                  pgtype.UUID
	SessionTokenHash    []byte
	SessionType         string
	PhotobookID         pgtype.UUID
	TokenVersionAtIssue int32
	ExpiresAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

// PR7: Session 認可機構の sqlc query 群。
//
// 設計参照:
//   - docs/design/auth/session/データモデル設計.md
//   - docs/plan/m2-session-auth-implementation-plan.md §9
//
// セキュリティ:
//   - すべての SELECT は revoked_at IS NULL AND expires_at > now() を条件に含める
//     （期限切れ / revoke 済 session を取り出してしまう経路を作らない）
//   - DELETE / UPDATE は WHERE 条件を必ず明示。アプリ層からの任意 SQL は許可しない
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.SessionTokenHash,
		arg.SessionType,
		arg.PhotobookID,
		arg.TokenVersionAtIssue,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
 WHERE (revoked_at IS NOT NULL AND revoked_at < now() - interval '30 days')
    OR (expires_at < now() - interval '7 days')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findActiveSessionByHash = `-- name: FindActiveSessionByHash :one
SELECT
    id,
    session_token_hash,
    session_type,
    photobook_id,
    token_version_at_issue,
    expires_at,
    created_at,
    last_used_at,
    revoked_at
FROM sessions
WHERE session_token_hash = $1
  AND session_type       = $2
  AND photobook_id       = $3
  AND revoked_at IS NULL
  AND expires_at > now()
`

type FindActiveSessionByHashParams struct {
	SessionTokenHash []byte
	SessionType      string
	PhotobookID      pgtype.UUID
}

func (q *Queries) FindActiveSessionByHash(ctx context.Context, arg FindActiveSessionByHashParams) (Session, error) {
	row := q.db.QueryRow(ctx, findActiveSessionByHash, arg.SessionTokenHash, arg.SessionType, arg.PhotobookID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionTokenHash,
		&i.SessionType,
		&i.PhotobookID,
		&i.TokenVersionAtIssue,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAllDraftsByPhotobook = `-- name: RevokeAllDraftsByPhotobook :execrows
UPDATE sessions
   SET revoked_at = now()
 WHERE photobook_id = $1
   AND session_type = 'draft'
   AND revoked_at IS NULL
`

func (q *Queries) RevokeAllDraftsByPhotobook(ctx context.Context, photobookID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllDraftsByPhotobook, photobookID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllManageByTokenVersion = `-- name: RevokeAllManageByTokenVersion :execrows
UPDATE sessions
   SET revoked_at = now()
 WHERE photobook_id           = $1
   AND session_type           = 'manage'
   AND token_version_at_issue <= $2
   AND revoked_at IS NULL
`

type RevokeAllManageByTokenVersionParams struct {
	PhotobookID         pgtype.UUID
	TokenVersionAtIssue int32
}

func (q *Queries) RevokeAllManageByTokenVersion(ctx context.Context, arg RevokeAllManageByTokenVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllManageByTokenVersion, arg.PhotobookID, arg.TokenVersionAtIssue)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionByID = `-- name: RevokeSessionByID :execrows
UPDATE sessions
   SET revoked_at = now()
 WHERE id = $1
   AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByID(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :execrows
UPDATE sessions
   SET last_used_at = now()
 WHERE id = $1
   AND revoked_at IS NULL
   AND expires_at > now()
`

func (q *Queries) TouchSession(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, touchSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
