// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :exec

INSERT INTO outbox_events (
    id,
    aggregate_type,
    aggregate_id,
    event_type,
    payload,
    status,
    available_at,
    attempts,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    'pending', $6, 0, $7, $7
)
`

type CreateOutboxEventParams struct {
	ID            pgtype.UUID
	AggregateType string
	AggregateID   pgtype.UUID
	EventType     string
	Payload       []byte
	AvailableAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

// PR30: Outbox events の sqlc query。
//
// 設計参照:
//   - docs/plan/m2-outbox-plan.md §7
//   - docs/design/cross-cutting/outbox.md
//
// セキュリティ:
//   - payload に Secret / token / Cookie / presigned URL / storage_key 完全値を入れない
//     （application 層の VO で担保、Repository は jsonb をそのまま受ける）
//   - last_error は CHECK 制約で 200 char 上限。PR31 worker が sanitize して書く
//
// 同一 TX で集約状態更新と一緒に呼び出される前提。
// status='pending' / available_at=now() / attempts=0 を default で書く。
func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.AvailableAt,
		arg.CreatedAt,
	)
	return err
}
