// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HealthCheck struct {
	ID        int32
	CheckedAt pgtype.Timestamptz
}

type Report struct {
	ID                               pgtype.UUID
	TargetPhotobookID                pgtype.UUID
	TargetPublicUrlSnapshot          string
	TargetTitleSnapshot              string
	TargetCreatorDisplayNameSnapshot *string
	Reason                           string
	Detail                           *string
	ReporterContact                  *string
	Status                           string
	SubmittedAt                      pgtype.Timestamptz
	ReviewedAt                       pgtype.Timestamptz
	ResolvedAt                       pgtype.Timestamptz
	ResolutionNote                   *string
	ResolvedByModerationActionID     pgtype.UUID
	SourceIpHash                     []byte
}
