// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :exec

INSERT INTO reports (
    id,
    target_photobook_id,
    target_public_url_snapshot,
    target_title_snapshot,
    target_creator_display_name_snapshot,
    reason,
    detail,
    reporter_contact,
    status,
    submitted_at,
    source_ip_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, 'submitted', $9, $10
)
`

type CreateReportParams struct {
	ID                               pgtype.UUID
	TargetPhotobookID                pgtype.UUID
	TargetPublicUrlSnapshot          string
	TargetTitleSnapshot              string
	TargetCreatorDisplayNameSnapshot *string
	Reason                           string
	Detail                           *string
	ReporterContact                  *string
	SubmittedAt                      pgtype.Timestamptz
	SourceIpHash                     []byte
}

// PR35b: Report 集約の sqlc query。
//
// 設計参照:
//   - docs/design/aggregates/report/データモデル設計.md §3 / §4
//   - docs/plan/m2-report-plan.md §5
//
// セキュリティ:
//   - reporter_contact / detail / source_ip_hash は DB から読めるが、
//     呼び出し側（cmd/ops 出力ホワイトリスト）で表示制御する
//   - Outbox payload には reporter_contact / detail / source_ip_hash を入れない
//     （UseCase 側で payload を組み立てる時点で除外）
//   - source_ip_hash 完全値は外部応答 / log / chat に出さない（cmd/ops は先頭 4 byte のみ表示）
//
// 同一 TX 内（SubmitReport UseCase）で outbox_events INSERT と一緒に呼ばれる前提。
// status='submitted' / submitted_at=$now を default で書く。
func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) error {
	_, err := q.db.Exec(ctx, createReport,
		arg.ID,
		arg.TargetPhotobookID,
		arg.TargetPublicUrlSnapshot,
		arg.TargetTitleSnapshot,
		arg.TargetCreatorDisplayNameSnapshot,
		arg.Reason,
		arg.Detail,
		arg.ReporterContact,
		arg.SubmittedAt,
		arg.SourceIpHash,
	)
	return err
}

const getReportByID = `-- name: GetReportByID :one
SELECT
    id, target_photobook_id,
    target_public_url_snapshot,
    target_title_snapshot,
    target_creator_display_name_snapshot,
    reason, detail, reporter_contact, status,
    submitted_at, reviewed_at, resolved_at, resolution_note,
    resolved_by_moderation_action_id, source_ip_hash
FROM reports
WHERE id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, id pgtype.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.TargetPhotobookID,
		&i.TargetPublicUrlSnapshot,
		&i.TargetTitleSnapshot,
		&i.TargetCreatorDisplayNameSnapshot,
		&i.Reason,
		&i.Detail,
		&i.ReporterContact,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ResolvedAt,
		&i.ResolutionNote,
		&i.ResolvedByModerationActionID,
		&i.SourceIpHash,
	)
	return i, err
}

const listReports = `-- name: ListReports :many
SELECT
    id, target_photobook_id,
    target_public_url_snapshot,
    target_title_snapshot,
    target_creator_display_name_snapshot,
    reason, detail, reporter_contact, status,
    submitted_at, reviewed_at, resolved_at, resolution_note,
    resolved_by_moderation_action_id, source_ip_hash
FROM reports
WHERE ($1::text = '' OR status = $1::text)
  AND ($2::text = '' OR reason = $2::text)
ORDER BY
    CASE WHEN reason = 'minor_safety_concern' AND status IN ('submitted','under_review') THEN 0
         WHEN status IN ('submitted','under_review') THEN 1
         ELSE 2
    END ASC,
    submitted_at DESC
LIMIT $3
OFFSET $4
`

type ListReportsParams struct {
	Column1 string
	Column2 string
	Limit   int32
	Offset  int32
}

// cmd/ops report list 用。status / reason フィルタ + minor_safety_concern 優先。
// minor_safety_concern を最優先で表示し、次に未対応（submitted）を新しい順、
// 残りは submitted_at DESC。$1 status filter（”=ALL）/ $2 reason filter（”=ALL）
// / $3 limit / $4 offset。
func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReports,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.TargetPhotobookID,
			&i.TargetPublicUrlSnapshot,
			&i.TargetTitleSnapshot,
			&i.TargetCreatorDisplayNameSnapshot,
			&i.Reason,
			&i.Detail,
			&i.ReporterContact,
			&i.Status,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ResolvedAt,
			&i.ResolutionNote,
			&i.ResolvedByModerationActionID,
			&i.SourceIpHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReportResolvedActionTaken = `-- name: MarkReportResolvedActionTaken :execrows
UPDATE reports
   SET status                            = 'resolved_action_taken',
       resolved_by_moderation_action_id  = $1,
       resolved_at                       = $2
 WHERE id = $3
   AND status IN ('submitted', 'under_review')
`

type MarkReportResolvedActionTakenParams struct {
	ModerationActionID pgtype.UUID
	ResolvedAt         pgtype.Timestamptz
	ID                 pgtype.UUID
}

// Moderation hide --source-report-id 連動用。
// 対象 status は submitted / under_review のみ（終端状態は再オープンしない、I4）。
// 0 行 UPDATE は呼び出し側で「既に終端 / 不在」として error 化。
func (q *Queries) MarkReportResolvedActionTaken(ctx context.Context, arg MarkReportResolvedActionTakenParams) (int64, error) {
	result, err := q.db.Exec(ctx, markReportResolvedActionTaken, arg.ModerationActionID, arg.ResolvedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
