// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ogp.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingOgp = `-- name: CreatePendingOgp :exec
INSERT INTO photobook_ogp_images (
    id, photobook_id, status, version,
    created_at, updated_at
) VALUES (
    $1, $2, 'pending', 1,
    $3, $3
)
`

type CreatePendingOgpParams struct {
	ID          pgtype.UUID
	PhotobookID pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

// 新規 pending row を 1 行 INSERT。photobook_id UNIQUE 違反は呼び出し側で扱う。
func (q *Queries) CreatePendingOgp(ctx context.Context, arg CreatePendingOgpParams) error {
	_, err := q.db.Exec(ctx, createPendingOgp, arg.ID, arg.PhotobookID, arg.CreatedAt)
	return err
}

const findOgpByPhotobookID = `-- name: FindOgpByPhotobookID :one

SELECT
    id, photobook_id, status, image_id, version,
    generated_at, failed_at, failure_reason,
    created_at, updated_at
FROM photobook_ogp_images
WHERE photobook_id = $1
`

// PR33b: photobook_ogp_images の sqlc query。
//
// 設計参照:
//   - docs/plan/m2-ogp-generation-plan.md §6 / §9
//   - docs/design/cross-cutting/ogp-generation.md §3 / §4
//
// セキュリティ:
//   - failure_reason は呼び出し側 VO で sanitize 済を渡す（200 char 上限、
//     危険語 redact、ogp_failure_reason VO 参照）
func (q *Queries) FindOgpByPhotobookID(ctx context.Context, photobookID pgtype.UUID) (PhotobookOgpImage, error) {
	row := q.db.QueryRow(ctx, findOgpByPhotobookID, photobookID)
	var i PhotobookOgpImage
	err := row.Scan(
		&i.ID,
		&i.PhotobookID,
		&i.Status,
		&i.ImageID,
		&i.Version,
		&i.GeneratedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingOgp = `-- name: ListPendingOgp :many
SELECT
    id, photobook_id, status, image_id, version,
    generated_at, failed_at, failure_reason,
    created_at, updated_at
FROM photobook_ogp_images
WHERE status IN ('pending', 'stale', 'failed')
ORDER BY updated_at ASC
LIMIT $1
`

// pickup query（status='pending' / 'stale' / 'failed'）。
// updated_at 古い順で limit。FOR UPDATE SKIP LOCKED は CLI single-runner 想定では
// 任意（PR33d で worker 連携時に再評価）。
func (q *Queries) ListPendingOgp(ctx context.Context, limit int32) ([]PhotobookOgpImage, error) {
	rows, err := q.db.Query(ctx, listPendingOgp, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PhotobookOgpImage
	for rows.Next() {
		var i PhotobookOgpImage
		if err := rows.Scan(
			&i.ID,
			&i.PhotobookID,
			&i.Status,
			&i.ImageID,
			&i.Version,
			&i.GeneratedAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOgpFailed = `-- name: MarkOgpFailed :exec
UPDATE photobook_ogp_images
SET
    status         = 'failed',
    failed_at      = $2,
    failure_reason = $3,
    updated_at     = $2
WHERE id = $1
  AND status IN ('pending', 'stale')
`

type MarkOgpFailedParams struct {
	ID            pgtype.UUID
	FailedAt      pgtype.Timestamptz
	FailureReason *string
}

// pending / stale → failed。failed_at / failure_reason 必須（呼び出し側で sanitize）。
func (q *Queries) MarkOgpFailed(ctx context.Context, arg MarkOgpFailedParams) error {
	_, err := q.db.Exec(ctx, markOgpFailed, arg.ID, arg.FailedAt, arg.FailureReason)
	return err
}

const markOgpGenerated = `-- name: MarkOgpGenerated :exec
UPDATE photobook_ogp_images
SET
    status        = 'generated',
    image_id      = $2,
    generated_at  = $3,
    updated_at    = $3,
    failed_at     = NULL,
    failure_reason = NULL
WHERE id = $1
  AND status IN ('pending', 'stale', 'failed')
`

type MarkOgpGeneratedParams struct {
	ID          pgtype.UUID
	ImageID     pgtype.UUID
	GeneratedAt pgtype.Timestamptz
}

// pending / stale → generated。image_id / generated_at 必須。
func (q *Queries) MarkOgpGenerated(ctx context.Context, arg MarkOgpGeneratedParams) error {
	_, err := q.db.Exec(ctx, markOgpGenerated, arg.ID, arg.ImageID, arg.GeneratedAt)
	return err
}

const markOgpStale = `-- name: MarkOgpStale :exec
UPDATE photobook_ogp_images
SET
    status     = 'stale',
    version    = version + 1,
    updated_at = $2
WHERE id = $1
  AND status IN ('generated', 'failed')
`

type MarkOgpStaleParams struct {
	ID        pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

// generated / failed → stale + version++（Photobook 更新時）。
func (q *Queries) MarkOgpStale(ctx context.Context, arg MarkOgpStaleParams) error {
	_, err := q.db.Exec(ctx, markOgpStale, arg.ID, arg.UpdatedAt)
	return err
}
