// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photobook_pages.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpPhotobookVersionForDraft = `-- name: BumpPhotobookVersionForDraft :execrows
UPDATE photobooks
   SET version    = version + 1,
       updated_at = $3
 WHERE id      = $1
   AND status  = 'draft'
   AND version = $2
`

type BumpPhotobookVersionForDraftParams struct {
	ID        pgtype.UUID
	Version   int32
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) BumpPhotobookVersionForDraft(ctx context.Context, arg BumpPhotobookVersionForDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, bumpPhotobookVersionForDraft, arg.ID, arg.Version, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearPhotobookCoverImage = `-- name: ClearPhotobookCoverImage :execrows
UPDATE photobooks
   SET cover_image_id = NULL,
       version        = version + 1,
       updated_at     = $3
 WHERE id      = $1
   AND status  = 'draft'
   AND version = $2
`

type ClearPhotobookCoverImageParams struct {
	ID        pgtype.UUID
	Version   int32
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ClearPhotobookCoverImage(ctx context.Context, arg ClearPhotobookCoverImageParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearPhotobookCoverImage, arg.ID, arg.Version, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countPhotobookPagesByPhotobookID = `-- name: CountPhotobookPagesByPhotobookID :one
SELECT COUNT(*)::int AS cnt
FROM photobook_pages
WHERE photobook_id = $1
`

func (q *Queries) CountPhotobookPagesByPhotobookID(ctx context.Context, photobookID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPhotobookPagesByPhotobookID, photobookID)
	var cnt int32
	err := row.Scan(&cnt)
	return cnt, err
}

const countPhotobookPhotosByPageID = `-- name: CountPhotobookPhotosByPageID :one
SELECT COUNT(*)::int AS cnt
FROM photobook_photos
WHERE page_id = $1
`

func (q *Queries) CountPhotobookPhotosByPageID(ctx context.Context, pageID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPhotobookPhotosByPageID, pageID)
	var cnt int32
	err := row.Scan(&cnt)
	return cnt, err
}

const createPhotobookPage = `-- name: CreatePhotobookPage :exec

INSERT INTO photobook_pages (
    id, photobook_id, display_order, caption, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreatePhotobookPageParams struct {
	ID           pgtype.UUID
	PhotobookID  pgtype.UUID
	DisplayOrder int32
	Caption      *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// PR19: Photobook の Page / Photo / PageMeta / Cover に対する sqlc query 群。
//
// 設計参照:
//   - docs/design/aggregates/photobook/データモデル設計.md
//   - docs/plan/m2-photobook-image-connection-plan.md §8.2
//
// セキュリティ:
//   - photobook UPDATE はすべて WHERE version=$expected かつ status='draft' を持ち、
//     0 行 UPDATE をアプリ層で OptimisticLockConflict / ErrNotDraft として扱う
func (q *Queries) CreatePhotobookPage(ctx context.Context, arg CreatePhotobookPageParams) error {
	_, err := q.db.Exec(ctx, createPhotobookPage,
		arg.ID,
		arg.PhotobookID,
		arg.DisplayOrder,
		arg.Caption,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createPhotobookPhoto = `-- name: CreatePhotobookPhoto :exec
INSERT INTO photobook_photos (
    id, page_id, image_id, display_order, caption, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreatePhotobookPhotoParams struct {
	ID           pgtype.UUID
	PageID       pgtype.UUID
	ImageID      pgtype.UUID
	DisplayOrder int32
	Caption      *string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreatePhotobookPhoto(ctx context.Context, arg CreatePhotobookPhotoParams) error {
	_, err := q.db.Exec(ctx, createPhotobookPhoto,
		arg.ID,
		arg.PageID,
		arg.ImageID,
		arg.DisplayOrder,
		arg.Caption,
		arg.CreatedAt,
	)
	return err
}

const deletePhotobookPage = `-- name: DeletePhotobookPage :execrows
DELETE FROM photobook_pages
WHERE id = $1
  AND photobook_id = $2
`

type DeletePhotobookPageParams struct {
	ID          pgtype.UUID
	PhotobookID pgtype.UUID
}

func (q *Queries) DeletePhotobookPage(ctx context.Context, arg DeletePhotobookPageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePhotobookPage, arg.ID, arg.PhotobookID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePhotobookPhoto = `-- name: DeletePhotobookPhoto :execrows
DELETE FROM photobook_photos
WHERE id = $1
  AND page_id = $2
`

type DeletePhotobookPhotoParams struct {
	ID     pgtype.UUID
	PageID pgtype.UUID
}

func (q *Queries) DeletePhotobookPhoto(ctx context.Context, arg DeletePhotobookPhotoParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePhotobookPhoto, arg.ID, arg.PageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findAvailableImageForPhotobook = `-- name: FindAvailableImageForPhotobook :one
SELECT id
FROM images
WHERE id                = $1
  AND owner_photobook_id = $2
  AND status            = 'available'
  AND deleted_at        IS NULL
FOR UPDATE
`

type FindAvailableImageForPhotobookParams struct {
	ID               pgtype.UUID
	OwnerPhotobookID pgtype.UUID
}

// Image が「対象 photobook 所有 + status=available + 未削除」を満たすかを返す。
// 戻り値が無ければ ErrNoRows を呼び出し側で ErrImageNotAttachable に変換する。
func (q *Queries) FindAvailableImageForPhotobook(ctx context.Context, arg FindAvailableImageForPhotobookParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findAvailableImageForPhotobook, arg.ID, arg.OwnerPhotobookID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findPhotobookPageByID = `-- name: FindPhotobookPageByID :one
SELECT id, photobook_id, display_order, caption, created_at, updated_at
FROM photobook_pages
WHERE id = $1
`

func (q *Queries) FindPhotobookPageByID(ctx context.Context, id pgtype.UUID) (PhotobookPage, error) {
	row := q.db.QueryRow(ctx, findPhotobookPageByID, id)
	var i PhotobookPage
	err := row.Scan(
		&i.ID,
		&i.PhotobookID,
		&i.DisplayOrder,
		&i.Caption,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPhotobookPageMetaByPageID = `-- name: FindPhotobookPageMetaByPageID :one
SELECT page_id, world, cast_list, photographer, note, event_date, created_at, updated_at
FROM photobook_page_metas
WHERE page_id = $1
`

func (q *Queries) FindPhotobookPageMetaByPageID(ctx context.Context, pageID pgtype.UUID) (PhotobookPageMeta, error) {
	row := q.db.QueryRow(ctx, findPhotobookPageMetaByPageID, pageID)
	var i PhotobookPageMeta
	err := row.Scan(
		&i.PageID,
		&i.World,
		&i.CastList,
		&i.Photographer,
		&i.Note,
		&i.EventDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPhotobookPhotoByID = `-- name: FindPhotobookPhotoByID :one
SELECT id, page_id, image_id, display_order, caption, created_at
FROM photobook_photos
WHERE id = $1
`

func (q *Queries) FindPhotobookPhotoByID(ctx context.Context, id pgtype.UUID) (PhotobookPhoto, error) {
	row := q.db.QueryRow(ctx, findPhotobookPhotoByID, id)
	var i PhotobookPhoto
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.ImageID,
		&i.DisplayOrder,
		&i.Caption,
		&i.CreatedAt,
	)
	return i, err
}

const listPhotobookPagesByPhotobookID = `-- name: ListPhotobookPagesByPhotobookID :many
SELECT id, photobook_id, display_order, caption, created_at, updated_at
FROM photobook_pages
WHERE photobook_id = $1
ORDER BY display_order ASC
`

func (q *Queries) ListPhotobookPagesByPhotobookID(ctx context.Context, photobookID pgtype.UUID) ([]PhotobookPage, error) {
	rows, err := q.db.Query(ctx, listPhotobookPagesByPhotobookID, photobookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PhotobookPage
	for rows.Next() {
		var i PhotobookPage
		if err := rows.Scan(
			&i.ID,
			&i.PhotobookID,
			&i.DisplayOrder,
			&i.Caption,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotobookPhotosByPageID = `-- name: ListPhotobookPhotosByPageID :many
SELECT id, page_id, image_id, display_order, caption, created_at
FROM photobook_photos
WHERE page_id = $1
ORDER BY display_order ASC
`

func (q *Queries) ListPhotobookPhotosByPageID(ctx context.Context, pageID pgtype.UUID) ([]PhotobookPhoto, error) {
	rows, err := q.db.Query(ctx, listPhotobookPhotosByPageID, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PhotobookPhoto
	for rows.Next() {
		var i PhotobookPhoto
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.ImageID,
			&i.DisplayOrder,
			&i.Caption,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPhotobookCoverImage = `-- name: SetPhotobookCoverImage :execrows
UPDATE photobooks
   SET cover_image_id = $2,
       version        = version + 1,
       updated_at     = $4
 WHERE id      = $1
   AND status  = 'draft'
   AND version = $3
`

type SetPhotobookCoverImageParams struct {
	ID           pgtype.UUID
	CoverImageID pgtype.UUID
	Version      int32
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) SetPhotobookCoverImage(ctx context.Context, arg SetPhotobookCoverImageParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPhotobookCoverImage,
		arg.ID,
		arg.CoverImageID,
		arg.Version,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePhotobookPageOrder = `-- name: UpdatePhotobookPageOrder :execrows
UPDATE photobook_pages
   SET display_order = $2,
       updated_at    = $3
 WHERE id = $1
`

type UpdatePhotobookPageOrderParams struct {
	ID           pgtype.UUID
	DisplayOrder int32
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdatePhotobookPageOrder(ctx context.Context, arg UpdatePhotobookPageOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePhotobookPageOrder, arg.ID, arg.DisplayOrder, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePhotobookPhotoOrder = `-- name: UpdatePhotobookPhotoOrder :execrows
UPDATE photobook_photos
   SET display_order = $2
 WHERE id = $1
`

type UpdatePhotobookPhotoOrderParams struct {
	ID           pgtype.UUID
	DisplayOrder int32
}

func (q *Queries) UpdatePhotobookPhotoOrder(ctx context.Context, arg UpdatePhotobookPhotoOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePhotobookPhotoOrder, arg.ID, arg.DisplayOrder)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPhotobookPageMeta = `-- name: UpsertPhotobookPageMeta :exec
INSERT INTO photobook_page_metas (
    page_id, world, cast_list, photographer, note, event_date, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (page_id) DO UPDATE
SET
    world        = EXCLUDED.world,
    cast_list    = EXCLUDED.cast_list,
    photographer = EXCLUDED.photographer,
    note         = EXCLUDED.note,
    event_date   = EXCLUDED.event_date,
    updated_at   = EXCLUDED.updated_at
`

type UpsertPhotobookPageMetaParams struct {
	PageID       pgtype.UUID
	World        *string
	CastList     []string
	Photographer *string
	Note         *string
	EventDate    pgtype.Date
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpsertPhotobookPageMeta(ctx context.Context, arg UpsertPhotobookPageMetaParams) error {
	_, err := q.db.Exec(ctx, upsertPhotobookPageMeta,
		arg.PageID,
		arg.World,
		arg.CastList,
		arg.Photographer,
		arg.Note,
		arg.EventDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
