// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photobook_pages.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkOffsetPagesInPhotobook = `-- name: BulkOffsetPagesInPhotobook :execrows
UPDATE photobook_pages
   SET display_order = display_order + 1000,
       updated_at    = $2
 WHERE photobook_id = $1
`

type BulkOffsetPagesInPhotobookParams struct {
	PhotobookID pgtype.UUID
	UpdatedAt   pgtype.Timestamptz
}

// BulkOffsetPagesInPhotobook: page reorder / split / merge の +1000 escape primitive (P-1)。
// photo 版 BulkOffsetPhotoOrdersOnPage と同じ思想で、UNIQUE (photobook_id, display_order)
// との衝突を一時的に回避するため、対象 photobook の **全 page** の display_order を +1000
// する。呼び出し側 (UseCase) は同 TX 内で各 page を新しい display_order に書き戻す。
// updated_at は呼び出し側で渡す ($now)。
func (q *Queries) BulkOffsetPagesInPhotobook(ctx context.Context, arg BulkOffsetPagesInPhotobookParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkOffsetPagesInPhotobook, arg.PhotobookID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bulkOffsetPhotoOrdersOnPage = `-- name: BulkOffsetPhotoOrdersOnPage :execrows
UPDATE photobook_photos
   SET display_order = display_order + 1000
 WHERE page_id = $1
`

// BulkOffsetPhotoOrdersOnPage: PR27 reorder 一時退避用。
// 同 page 内の全 photo の display_order を +1000 オフセットして UNIQUE 衝突を一時的に回避する。
// 呼び出し側は同 TX 内で各 photo を新 display_order に書き戻す。
func (q *Queries) BulkOffsetPhotoOrdersOnPage(ctx context.Context, pageID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, bulkOffsetPhotoOrdersOnPage, pageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bumpPhotobookVersionForDraft = `-- name: BumpPhotobookVersionForDraft :execrows
UPDATE photobooks
   SET version    = version + 1,
       updated_at = $3
 WHERE id      = $1
   AND status  = 'draft'
   AND version = $2
`

type BumpPhotobookVersionForDraftParams struct {
	ID        pgtype.UUID
	Version   int32
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) BumpPhotobookVersionForDraft(ctx context.Context, arg BumpPhotobookVersionForDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, bumpPhotobookVersionForDraft, arg.ID, arg.Version, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearPhotobookCoverImage = `-- name: ClearPhotobookCoverImage :execrows
UPDATE photobooks
   SET cover_image_id = NULL,
       version        = version + 1,
       updated_at     = $3
 WHERE id      = $1
   AND status  = 'draft'
   AND version = $2
`

type ClearPhotobookCoverImageParams struct {
	ID        pgtype.UUID
	Version   int32
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ClearPhotobookCoverImage(ctx context.Context, arg ClearPhotobookCoverImageParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearPhotobookCoverImage, arg.ID, arg.Version, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countPhotobookPagesByPhotobookID = `-- name: CountPhotobookPagesByPhotobookID :one
SELECT COUNT(*)::int AS cnt
FROM photobook_pages
WHERE photobook_id = $1
`

func (q *Queries) CountPhotobookPagesByPhotobookID(ctx context.Context, photobookID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPhotobookPagesByPhotobookID, photobookID)
	var cnt int32
	err := row.Scan(&cnt)
	return cnt, err
}

const countPhotobookPhotosByPageID = `-- name: CountPhotobookPhotosByPageID :one
SELECT COUNT(*)::int AS cnt
FROM photobook_photos
WHERE page_id = $1
`

func (q *Queries) CountPhotobookPhotosByPageID(ctx context.Context, pageID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPhotobookPhotosByPageID, pageID)
	var cnt int32
	err := row.Scan(&cnt)
	return cnt, err
}

const createPhotobookPage = `-- name: CreatePhotobookPage :exec

INSERT INTO photobook_pages (
    id, photobook_id, display_order, caption, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreatePhotobookPageParams struct {
	ID           pgtype.UUID
	PhotobookID  pgtype.UUID
	DisplayOrder int32
	Caption      *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// PR19: Photobook の Page / Photo / PageMeta / Cover に対する sqlc query 群。
//
// 設計参照:
//   - docs/design/aggregates/photobook/データモデル設計.md
//   - docs/plan/m2-photobook-image-connection-plan.md §8.2
//
// セキュリティ:
//   - photobook UPDATE はすべて WHERE version=$expected かつ status='draft' を持ち、
//     0 行 UPDATE をアプリ層で OptimisticLockConflict / ErrNotDraft として扱う
func (q *Queries) CreatePhotobookPage(ctx context.Context, arg CreatePhotobookPageParams) error {
	_, err := q.db.Exec(ctx, createPhotobookPage,
		arg.ID,
		arg.PhotobookID,
		arg.DisplayOrder,
		arg.Caption,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createPhotobookPhoto = `-- name: CreatePhotobookPhoto :exec
INSERT INTO photobook_photos (
    id, page_id, image_id, display_order, caption, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreatePhotobookPhotoParams struct {
	ID           pgtype.UUID
	PageID       pgtype.UUID
	ImageID      pgtype.UUID
	DisplayOrder int32
	Caption      *string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreatePhotobookPhoto(ctx context.Context, arg CreatePhotobookPhotoParams) error {
	_, err := q.db.Exec(ctx, createPhotobookPhoto,
		arg.ID,
		arg.PageID,
		arg.ImageID,
		arg.DisplayOrder,
		arg.Caption,
		arg.CreatedAt,
	)
	return err
}

const deletePhotobookPage = `-- name: DeletePhotobookPage :execrows
DELETE FROM photobook_pages
WHERE id = $1
  AND photobook_id = $2
`

type DeletePhotobookPageParams struct {
	ID          pgtype.UUID
	PhotobookID pgtype.UUID
}

func (q *Queries) DeletePhotobookPage(ctx context.Context, arg DeletePhotobookPageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePhotobookPage, arg.ID, arg.PhotobookID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePhotobookPhoto = `-- name: DeletePhotobookPhoto :execrows
DELETE FROM photobook_photos
WHERE id = $1
  AND page_id = $2
`

type DeletePhotobookPhotoParams struct {
	ID     pgtype.UUID
	PageID pgtype.UUID
}

func (q *Queries) DeletePhotobookPhoto(ctx context.Context, arg DeletePhotobookPhotoParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePhotobookPhoto, arg.ID, arg.PageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findAvailableImageForPhotobook = `-- name: FindAvailableImageForPhotobook :one
SELECT id
FROM images
WHERE id                = $1
  AND owner_photobook_id = $2
  AND status            = 'available'
  AND deleted_at        IS NULL
FOR UPDATE
`

type FindAvailableImageForPhotobookParams struct {
	ID               pgtype.UUID
	OwnerPhotobookID pgtype.UUID
}

// Image が「対象 photobook 所有 + status=available + 未削除」を満たすかを返す。
// 戻り値が無ければ ErrNoRows を呼び出し側で ErrImageNotAttachable に変換する。
func (q *Queries) FindAvailableImageForPhotobook(ctx context.Context, arg FindAvailableImageForPhotobookParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findAvailableImageForPhotobook, arg.ID, arg.OwnerPhotobookID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findPhotobookPageByID = `-- name: FindPhotobookPageByID :one
SELECT id, photobook_id, display_order, caption, created_at, updated_at
FROM photobook_pages
WHERE id = $1
`

func (q *Queries) FindPhotobookPageByID(ctx context.Context, id pgtype.UUID) (PhotobookPage, error) {
	row := q.db.QueryRow(ctx, findPhotobookPageByID, id)
	var i PhotobookPage
	err := row.Scan(
		&i.ID,
		&i.PhotobookID,
		&i.DisplayOrder,
		&i.Caption,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPhotobookPageMetaByPageID = `-- name: FindPhotobookPageMetaByPageID :one
SELECT page_id, world, cast_list, photographer, note, event_date, created_at, updated_at
FROM photobook_page_metas
WHERE page_id = $1
`

func (q *Queries) FindPhotobookPageMetaByPageID(ctx context.Context, pageID pgtype.UUID) (PhotobookPageMeta, error) {
	row := q.db.QueryRow(ctx, findPhotobookPageMetaByPageID, pageID)
	var i PhotobookPageMeta
	err := row.Scan(
		&i.PageID,
		&i.World,
		&i.CastList,
		&i.Photographer,
		&i.Note,
		&i.EventDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPhotobookPhotoByID = `-- name: FindPhotobookPhotoByID :one
SELECT id, page_id, image_id, display_order, caption, created_at
FROM photobook_photos
WHERE id = $1
`

func (q *Queries) FindPhotobookPhotoByID(ctx context.Context, id pgtype.UUID) (PhotobookPhoto, error) {
	row := q.db.QueryRow(ctx, findPhotobookPhotoByID, id)
	var i PhotobookPhoto
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.ImageID,
		&i.DisplayOrder,
		&i.Caption,
		&i.CreatedAt,
	)
	return i, err
}

const findPhotobookPhotoWithPhotobookID = `-- name: FindPhotobookPhotoWithPhotobookID :one
SELECT pp.id            AS id,
       pp.page_id       AS page_id,
       pp.image_id      AS image_id,
       pp.display_order AS display_order,
       pp.caption       AS caption,
       pp.created_at    AS created_at,
       pg.photobook_id  AS photobook_id
FROM photobook_photos pp
JOIN photobook_pages  pg ON pg.id = pp.page_id
WHERE pp.id = $1
`

type FindPhotobookPhotoWithPhotobookIDRow struct {
	ID           pgtype.UUID
	PageID       pgtype.UUID
	ImageID      pgtype.UUID
	DisplayOrder int32
	Caption      *string
	CreatedAt    pgtype.Timestamptz
	PhotobookID  pgtype.UUID
}

// FindPhotobookPhotoWithPhotobookID: photo + 所属 photobook_id を JOIN で同時取得 (P-1)。
// ownership 検証用。row 不在は呼び出し側で ErrPhotoNotFound に変換。
// (caption / image_id / display_order も合わせて返すため、FindPhotobookPhotoByID の
//
//	上位互換として move ロジックで利用しやすい)
func (q *Queries) FindPhotobookPhotoWithPhotobookID(ctx context.Context, id pgtype.UUID) (FindPhotobookPhotoWithPhotobookIDRow, error) {
	row := q.db.QueryRow(ctx, findPhotobookPhotoWithPhotobookID, id)
	var i FindPhotobookPhotoWithPhotobookIDRow
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.ImageID,
		&i.DisplayOrder,
		&i.Caption,
		&i.CreatedAt,
		&i.PhotobookID,
	)
	return i, err
}

const listAvailableUnattachedImageIDsByPhotobook = `-- name: ListAvailableUnattachedImageIDsByPhotobook :many
SELECT i.id
FROM images i
WHERE i.owner_photobook_id = $1
  AND i.status            = 'available'
  AND i.deleted_at        IS NULL
  AND NOT EXISTS (
      SELECT 1
      FROM photobook_photos pp
      JOIN photobook_pages pg ON pp.page_id = pg.id
      WHERE pg.photobook_id = $1
        AND pp.image_id     = i.id
  )
ORDER BY i.uploaded_at ASC
`

// /prepare/attach-images（plan v2 §3.4 / §5）で「photobook の available + 未 attach な
// image」を bulk 取得する。
// ・status='available' のみ（uploading / processing / failed / deleted / purged は対象外）
// ・既に photobook_photos に attach 済の image は NOT EXISTS で除外
//
//	（photobook_photos には photobook_id 直接 column が無いため photobook_pages 経由で JOIN）
//
// ・並び順は uploaded_at ASC（attach 順序の決定論性を担保）
func (q *Queries) ListAvailableUnattachedImageIDsByPhotobook(ctx context.Context, ownerPhotobookID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAvailableUnattachedImageIDsByPhotobook, ownerPhotobookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotobookPagesByPhotobookID = `-- name: ListPhotobookPagesByPhotobookID :many
SELECT id, photobook_id, display_order, caption, created_at, updated_at
FROM photobook_pages
WHERE photobook_id = $1
ORDER BY display_order ASC
`

func (q *Queries) ListPhotobookPagesByPhotobookID(ctx context.Context, photobookID pgtype.UUID) ([]PhotobookPage, error) {
	rows, err := q.db.Query(ctx, listPhotobookPagesByPhotobookID, photobookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PhotobookPage
	for rows.Next() {
		var i PhotobookPage
		if err := rows.Scan(
			&i.ID,
			&i.PhotobookID,
			&i.DisplayOrder,
			&i.Caption,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotobookPhotosByPageID = `-- name: ListPhotobookPhotosByPageID :many
SELECT id, page_id, image_id, display_order, caption, created_at
FROM photobook_photos
WHERE page_id = $1
ORDER BY display_order ASC
`

func (q *Queries) ListPhotobookPhotosByPageID(ctx context.Context, pageID pgtype.UUID) ([]PhotobookPhoto, error) {
	rows, err := q.db.Query(ctx, listPhotobookPhotosByPageID, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PhotobookPhoto
	for rows.Next() {
		var i PhotobookPhoto
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.ImageID,
			&i.DisplayOrder,
			&i.Caption,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPhotobookCoverImage = `-- name: SetPhotobookCoverImage :execrows
UPDATE photobooks
   SET cover_image_id = $2,
       version        = version + 1,
       updated_at     = $4
 WHERE id      = $1
   AND status  = 'draft'
   AND version = $3
`

type SetPhotobookCoverImageParams struct {
	ID           pgtype.UUID
	CoverImageID pgtype.UUID
	Version      int32
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) SetPhotobookCoverImage(ctx context.Context, arg SetPhotobookCoverImageParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPhotobookCoverImage,
		arg.ID,
		arg.CoverImageID,
		arg.Version,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePhotobookPageCaption = `-- name: UpdatePhotobookPageCaption :execrows

UPDATE photobook_pages
   SET caption    = $2,
       updated_at = $3
 WHERE id           = $1
   AND photobook_id = $4
`

type UpdatePhotobookPageCaptionParams struct {
	ID          pgtype.UUID
	Caption     *string
	UpdatedAt   pgtype.Timestamptz
	PhotobookID pgtype.UUID
}

// ============================================================================
// STOP P-1: page split / merge / move primitives (m2-edit Phase A)
// ----------------------------------------------------------------------------
// 計画: docs/plan/m2-edit-page-split-and-preview-plan.md §2.3 / §2.4
// 方針: 薄い primitive に保つ。draft check / version+1 / 30 page 上限 / reason mapping
//
//	はすべて UseCase 層 (STOP P-2) で扱う。本 query は SQL レベルの ownership 検証
//	(page は photobook_id 直 column、photo は photobook_pages 経由 JOIN) のみ行う。
//
// ============================================================================
// UpdatePhotobookPageCaption: page caption の単独編集 (P-1)。
// caption は VARCHAR/TEXT で NULL 許容。len validation は domain.NewCaption に委譲。
// WHERE 句で photobook_id 所属を検証 → 別 photobook の page を誤更新しない。
// 0 行 → ErrPageNotFound (Repository 層で変換)。
func (q *Queries) UpdatePhotobookPageCaption(ctx context.Context, arg UpdatePhotobookPageCaptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePhotobookPageCaption,
		arg.ID,
		arg.Caption,
		arg.UpdatedAt,
		arg.PhotobookID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePhotobookPageOrder = `-- name: UpdatePhotobookPageOrder :execrows
UPDATE photobook_pages
   SET display_order = $2,
       updated_at    = $3
 WHERE id = $1
`

type UpdatePhotobookPageOrderParams struct {
	ID           pgtype.UUID
	DisplayOrder int32
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdatePhotobookPageOrder(ctx context.Context, arg UpdatePhotobookPageOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePhotobookPageOrder, arg.ID, arg.DisplayOrder, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePhotobookPhotoCaption = `-- name: UpdatePhotobookPhotoCaption :execrows
UPDATE photobook_photos
   SET caption = $2
 WHERE id = $1
`

type UpdatePhotobookPhotoCaptionParams struct {
	ID      pgtype.UUID
	Caption *string
}

// UpdatePhotobookPhotoCaption: PR27 photo caption 単独編集。
// caption は VARCHAR/TEXT で NULL 許容（空 caption は NULL として保存）。
func (q *Queries) UpdatePhotobookPhotoCaption(ctx context.Context, arg UpdatePhotobookPhotoCaptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePhotobookPhotoCaption, arg.ID, arg.Caption)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePhotobookPhotoOrder = `-- name: UpdatePhotobookPhotoOrder :execrows
UPDATE photobook_photos
   SET display_order = $2
 WHERE id = $1
`

type UpdatePhotobookPhotoOrderParams struct {
	ID           pgtype.UUID
	DisplayOrder int32
}

// 注意: 単純な単一行 UPDATE。UNIQUE (page_id, display_order) と衝突する
// new_order が既に他 photo に取られていると 23505 を返す。
// MVP の Reorder は「新規 order が空いている」前提で運用する。
// 二者間 swap や complex reorder は呼び出し側で：
//  1. 一時退避（例: 大きな offset 値 1000+ に一旦逃がす、CHECK display_order >= 0 のため）
//  2. 順次 UPDATE
//
// のパターンを実装する。DEFERRABLE UNIQUE は MVP では採用しない（PR19 計画 / Audit）。
func (q *Queries) UpdatePhotobookPhotoOrder(ctx context.Context, arg UpdatePhotobookPhotoOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePhotobookPhotoOrder, arg.ID, arg.DisplayOrder)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePhotobookPhotoPageAndOrder = `-- name: UpdatePhotobookPhotoPageAndOrder :execrows
UPDATE photobook_photos
   SET page_id       = $2,
       display_order = $3
 WHERE id = $1
`

type UpdatePhotobookPhotoPageAndOrderParams struct {
	ID           pgtype.UUID
	PageID       pgtype.UUID
	DisplayOrder int32
}

// UpdatePhotobookPhotoPageAndOrder: photo の page_id + display_order を同時更新 (P-1)。
// 単純な単一行 UPDATE。UNIQUE (page_id, display_order) と衝突する new_order が target_page
// に既に取られていれば 23505 を返すため、呼び出し側 (UseCase) は事前に
// BulkOffsetPhotoOrdersOnPage(target_page) で escape してから呼ぶ。
// ownership (photo / target page が同 photobook 配下か) は Repository 層で
// FindPhotobookPhotoWithPhotobookID + FindPhotobookPageByID により検証する。
// 0 行 → ErrPhotoNotFound (Repository 層で変換)。
func (q *Queries) UpdatePhotobookPhotoPageAndOrder(ctx context.Context, arg UpdatePhotobookPhotoPageAndOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePhotobookPhotoPageAndOrder, arg.ID, arg.PageID, arg.DisplayOrder)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPhotobookPageMeta = `-- name: UpsertPhotobookPageMeta :exec
INSERT INTO photobook_page_metas (
    page_id, world, cast_list, photographer, note, event_date, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (page_id) DO UPDATE
SET
    world        = EXCLUDED.world,
    cast_list    = EXCLUDED.cast_list,
    photographer = EXCLUDED.photographer,
    note         = EXCLUDED.note,
    event_date   = EXCLUDED.event_date,
    updated_at   = EXCLUDED.updated_at
`

type UpsertPhotobookPageMetaParams struct {
	PageID       pgtype.UUID
	World        *string
	CastList     []string
	Photographer *string
	Note         *string
	EventDate    pgtype.Date
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpsertPhotobookPageMeta(ctx context.Context, arg UpsertPhotobookPageMetaParams) error {
	_, err := q.db.Exec(ctx, upsertPhotobookPageMeta,
		arg.PageID,
		arg.World,
		arg.CastList,
		arg.Photographer,
		arg.Note,
		arg.EventDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
