// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photobook.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDraftPhotobook = `-- name: CreateDraftPhotobook :exec

INSERT INTO photobooks (
    id,
    type,
    title,
    description,
    layout,
    opening_style,
    visibility,
    sensitive,
    rights_agreed,
    rights_agreed_at,
    creator_display_name,
    creator_x_id,
    cover_title,
    cover_image_id,
    public_url_slug,
    manage_url_token_hash,
    manage_url_token_version,
    draft_edit_token_hash,
    draft_expires_at,
    status,
    hidden_by_operator,
    version,
    published_at,
    created_at,
    updated_at,
    deleted_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, NULL, NULL, $15, $16, $17,
    'draft', false, $18, NULL, $19, $20, NULL
)
`

type CreateDraftPhotobookParams struct {
	ID                    pgtype.UUID
	Type                  string
	Title                 string
	Description           *string
	Layout                string
	OpeningStyle          string
	Visibility            string
	Sensitive             bool
	RightsAgreed          bool
	RightsAgreedAt        pgtype.Timestamptz
	CreatorDisplayName    string
	CreatorXID            *string
	CoverTitle            *string
	CoverImageID          pgtype.UUID
	ManageUrlTokenVersion int32
	DraftEditTokenHash    []byte
	DraftExpiresAt        pgtype.Timestamptz
	Version               int32
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

// PR9a: Photobook 集約の sqlc query 群。
//
// 設計参照:
//   - docs/design/aggregates/photobook/データモデル設計.md
//   - docs/plan/m2-photobook-session-integration-plan.md §8
//
// セキュリティ:
//   - すべての UPDATE は version = $expectedVersion を WHERE に含める（楽観ロック）
//   - 0 行 UPDATE はアプリ層で OptimisticLockConflict として扱う
//   - draft 検索は draft_expires_at > now() を条件に含め、期限切れを抜け出させない
func (q *Queries) CreateDraftPhotobook(ctx context.Context, arg CreateDraftPhotobookParams) error {
	_, err := q.db.Exec(ctx, createDraftPhotobook,
		arg.ID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Layout,
		arg.OpeningStyle,
		arg.Visibility,
		arg.Sensitive,
		arg.RightsAgreed,
		arg.RightsAgreedAt,
		arg.CreatorDisplayName,
		arg.CreatorXID,
		arg.CoverTitle,
		arg.CoverImageID,
		arg.ManageUrlTokenVersion,
		arg.DraftEditTokenHash,
		arg.DraftExpiresAt,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const findPhotobookByDraftEditTokenHash = `-- name: FindPhotobookByDraftEditTokenHash :one
SELECT
    id, type, title, description, layout, opening_style, visibility,
    sensitive, rights_agreed, rights_agreed_at, creator_display_name,
    creator_x_id, cover_title, cover_image_id, public_url_slug,
    manage_url_token_hash, manage_url_token_version, draft_edit_token_hash,
    draft_expires_at, status, hidden_by_operator, version, published_at,
    created_at, updated_at, deleted_at
FROM photobooks
WHERE draft_edit_token_hash = $1
  AND status = 'draft'
  AND draft_expires_at > now()
`

func (q *Queries) FindPhotobookByDraftEditTokenHash(ctx context.Context, draftEditTokenHash []byte) (Photobook, error) {
	row := q.db.QueryRow(ctx, findPhotobookByDraftEditTokenHash, draftEditTokenHash)
	var i Photobook
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Layout,
		&i.OpeningStyle,
		&i.Visibility,
		&i.Sensitive,
		&i.RightsAgreed,
		&i.RightsAgreedAt,
		&i.CreatorDisplayName,
		&i.CreatorXID,
		&i.CoverTitle,
		&i.CoverImageID,
		&i.PublicUrlSlug,
		&i.ManageUrlTokenHash,
		&i.ManageUrlTokenVersion,
		&i.DraftEditTokenHash,
		&i.DraftExpiresAt,
		&i.Status,
		&i.HiddenByOperator,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findPhotobookByID = `-- name: FindPhotobookByID :one
SELECT
    id, type, title, description, layout, opening_style, visibility,
    sensitive, rights_agreed, rights_agreed_at, creator_display_name,
    creator_x_id, cover_title, cover_image_id, public_url_slug,
    manage_url_token_hash, manage_url_token_version, draft_edit_token_hash,
    draft_expires_at, status, hidden_by_operator, version, published_at,
    created_at, updated_at, deleted_at
FROM photobooks
WHERE id = $1
`

func (q *Queries) FindPhotobookByID(ctx context.Context, id pgtype.UUID) (Photobook, error) {
	row := q.db.QueryRow(ctx, findPhotobookByID, id)
	var i Photobook
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Layout,
		&i.OpeningStyle,
		&i.Visibility,
		&i.Sensitive,
		&i.RightsAgreed,
		&i.RightsAgreedAt,
		&i.CreatorDisplayName,
		&i.CreatorXID,
		&i.CoverTitle,
		&i.CoverImageID,
		&i.PublicUrlSlug,
		&i.ManageUrlTokenHash,
		&i.ManageUrlTokenVersion,
		&i.DraftEditTokenHash,
		&i.DraftExpiresAt,
		&i.Status,
		&i.HiddenByOperator,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findPhotobookByManageUrlTokenHash = `-- name: FindPhotobookByManageUrlTokenHash :one
SELECT
    id, type, title, description, layout, opening_style, visibility,
    sensitive, rights_agreed, rights_agreed_at, creator_display_name,
    creator_x_id, cover_title, cover_image_id, public_url_slug,
    manage_url_token_hash, manage_url_token_version, draft_edit_token_hash,
    draft_expires_at, status, hidden_by_operator, version, published_at,
    created_at, updated_at, deleted_at
FROM photobooks
WHERE manage_url_token_hash = $1
  AND status IN ('published', 'deleted')
`

func (q *Queries) FindPhotobookByManageUrlTokenHash(ctx context.Context, manageUrlTokenHash []byte) (Photobook, error) {
	row := q.db.QueryRow(ctx, findPhotobookByManageUrlTokenHash, manageUrlTokenHash)
	var i Photobook
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Layout,
		&i.OpeningStyle,
		&i.Visibility,
		&i.Sensitive,
		&i.RightsAgreed,
		&i.RightsAgreedAt,
		&i.CreatorDisplayName,
		&i.CreatorXID,
		&i.CoverTitle,
		&i.CoverImageID,
		&i.PublicUrlSlug,
		&i.ManageUrlTokenHash,
		&i.ManageUrlTokenVersion,
		&i.DraftEditTokenHash,
		&i.DraftExpiresAt,
		&i.Status,
		&i.HiddenByOperator,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findPhotobookBySlug = `-- name: FindPhotobookBySlug :one
SELECT
    id, type, title, description, layout, opening_style, visibility,
    sensitive, rights_agreed, rights_agreed_at, creator_display_name,
    creator_x_id, cover_title, cover_image_id, public_url_slug,
    manage_url_token_hash, manage_url_token_version, draft_edit_token_hash,
    draft_expires_at, status, hidden_by_operator, version, published_at,
    created_at, updated_at, deleted_at
FROM photobooks
WHERE public_url_slug = $1
  AND status = 'published'
  AND hidden_by_operator = false
`

func (q *Queries) FindPhotobookBySlug(ctx context.Context, publicUrlSlug *string) (Photobook, error) {
	row := q.db.QueryRow(ctx, findPhotobookBySlug, publicUrlSlug)
	var i Photobook
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Layout,
		&i.OpeningStyle,
		&i.Visibility,
		&i.Sensitive,
		&i.RightsAgreed,
		&i.RightsAgreedAt,
		&i.CreatorDisplayName,
		&i.CreatorXID,
		&i.CoverTitle,
		&i.CoverImageID,
		&i.PublicUrlSlug,
		&i.ManageUrlTokenHash,
		&i.ManageUrlTokenVersion,
		&i.DraftEditTokenHash,
		&i.DraftExpiresAt,
		&i.Status,
		&i.HiddenByOperator,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findPhotobookBySlugAny = `-- name: FindPhotobookBySlugAny :one
SELECT
    id, type, title, description, layout, opening_style, visibility,
    sensitive, rights_agreed, rights_agreed_at, creator_display_name,
    creator_x_id, cover_title, cover_image_id, public_url_slug,
    manage_url_token_hash, manage_url_token_version, draft_edit_token_hash,
    draft_expires_at, status, hidden_by_operator, version, published_at,
    created_at, updated_at, deleted_at
FROM photobooks
WHERE public_url_slug = $1
`

// FindPhotobookBySlugAny: slug 一致のみで status / hidden_by_operator を判別しない。
// PR25a 公開 Viewer は status / hidden / visibility を usecase 側で判定して
// 200 / 410 / 404 を分岐するため、より permissive な query を別に置く。
func (q *Queries) FindPhotobookBySlugAny(ctx context.Context, publicUrlSlug *string) (Photobook, error) {
	row := q.db.QueryRow(ctx, findPhotobookBySlugAny, publicUrlSlug)
	var i Photobook
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Layout,
		&i.OpeningStyle,
		&i.Visibility,
		&i.Sensitive,
		&i.RightsAgreed,
		&i.RightsAgreedAt,
		&i.CreatorDisplayName,
		&i.CreatorXID,
		&i.CoverTitle,
		&i.CoverImageID,
		&i.PublicUrlSlug,
		&i.ManageUrlTokenHash,
		&i.ManageUrlTokenVersion,
		&i.DraftEditTokenHash,
		&i.DraftExpiresAt,
		&i.Status,
		&i.HiddenByOperator,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPhotobookForOps = `-- name: GetPhotobookForOps :one
SELECT
    id,
    type,
    title,
    description,
    layout,
    opening_style,
    visibility,
    creator_display_name,
    creator_x_id,
    cover_title,
    public_url_slug,
    status,
    hidden_by_operator,
    version,
    published_at,
    created_at,
    updated_at
FROM photobooks
WHERE id = $1
`

type GetPhotobookForOpsRow struct {
	ID                 pgtype.UUID
	Type               string
	Title              string
	Description        *string
	Layout             string
	OpeningStyle       string
	Visibility         string
	CreatorDisplayName string
	CreatorXID         *string
	CoverTitle         *string
	PublicUrlSlug      *string
	Status             string
	HiddenByOperator   bool
	Version            int32
	PublishedAt        pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

// PR34b: cmd/ops show 用。raw token / hash 系は返さない。
func (q *Queries) GetPhotobookForOps(ctx context.Context, id pgtype.UUID) (GetPhotobookForOpsRow, error) {
	row := q.db.QueryRow(ctx, getPhotobookForOps, id)
	var i GetPhotobookForOpsRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Layout,
		&i.OpeningStyle,
		&i.Visibility,
		&i.CreatorDisplayName,
		&i.CreatorXID,
		&i.CoverTitle,
		&i.PublicUrlSlug,
		&i.Status,
		&i.HiddenByOperator,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHiddenPhotobooksForOps = `-- name: ListHiddenPhotobooksForOps :many
SELECT
    id,
    public_url_slug,
    title,
    creator_display_name,
    visibility,
    status,
    version,
    published_at,
    updated_at
FROM photobooks
WHERE hidden_by_operator = true
ORDER BY updated_at DESC
LIMIT $1
OFFSET $2
`

type ListHiddenPhotobooksForOpsParams struct {
	Limit  int32
	Offset int32
}

type ListHiddenPhotobooksForOpsRow struct {
	ID                 pgtype.UUID
	PublicUrlSlug      *string
	Title              string
	CreatorDisplayName string
	Visibility         string
	Status             string
	Version            int32
	PublishedAt        pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

// PR34b: hidden_by_operator=true な published photobook の一覧（cmd/ops list-hidden 用）。
// raw token / hash 系は返さない（呼び出し側で出さなくてよい列のみ select）。
func (q *Queries) ListHiddenPhotobooksForOps(ctx context.Context, arg ListHiddenPhotobooksForOpsParams) ([]ListHiddenPhotobooksForOpsRow, error) {
	rows, err := q.db.Query(ctx, listHiddenPhotobooksForOps, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHiddenPhotobooksForOpsRow
	for rows.Next() {
		var i ListHiddenPhotobooksForOpsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicUrlSlug,
			&i.Title,
			&i.CreatorDisplayName,
			&i.Visibility,
			&i.Status,
			&i.Version,
			&i.PublishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishPhotobookFromDraft = `-- name: PublishPhotobookFromDraft :execrows
UPDATE photobooks
   SET status                   = 'published',
       public_url_slug          = $2,
       manage_url_token_hash    = $3,
       manage_url_token_version = 0,
       draft_edit_token_hash    = NULL,
       draft_expires_at         = NULL,
       published_at             = $4,
       rights_agreed            = true,
       rights_agreed_at         = $4,
       updated_at               = $4,
       version                  = version + 1
 WHERE id      = $1
   AND status  = 'draft'
   AND version = $5
`

type PublishPhotobookFromDraftParams struct {
	ID                 pgtype.UUID
	PublicUrlSlug      *string
	ManageUrlTokenHash []byte
	PublishedAt        pgtype.Timestamptz
	Version            int32
}

// 2026-05-03 STOP α P0 v2: 同 TX で rights_agreed=true / rights_agreed_at=$4 を保存。
// /edit publish UI の同意チェック → UseCase が pb.WithRightsAgreed(now) で domain を更新 →
// 本 SQL で永続化、までを 1 つの operation として扱う（業務知識 v4 §3.1）。
// 同意のみ残って publish 失敗 / publish のみ通って同意未保存の状態を作らない。
func (q *Queries) PublishPhotobookFromDraft(ctx context.Context, arg PublishPhotobookFromDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, publishPhotobookFromDraft,
		arg.ID,
		arg.PublicUrlSlug,
		arg.ManageUrlTokenHash,
		arg.PublishedAt,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reissuePhotobookManageUrl = `-- name: ReissuePhotobookManageUrl :execrows
UPDATE photobooks
   SET manage_url_token_hash    = $2,
       manage_url_token_version = manage_url_token_version + 1,
       updated_at               = now(),
       version                  = version + 1
 WHERE id      = $1
   AND status  IN ('published', 'deleted')
   AND version = $3
`

type ReissuePhotobookManageUrlParams struct {
	ID                 pgtype.UUID
	ManageUrlTokenHash []byte
	Version            int32
}

func (q *Queries) ReissuePhotobookManageUrl(ctx context.Context, arg ReissuePhotobookManageUrlParams) (int64, error) {
	result, err := q.db.Exec(ctx, reissuePhotobookManageUrl, arg.ID, arg.ManageUrlTokenHash, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPhotobookHiddenByOperator = `-- name: SetPhotobookHiddenByOperator :execrows
UPDATE photobooks
   SET hidden_by_operator = $2,
       updated_at         = $3
 WHERE id                 = $1
   AND status             = 'published'
   AND hidden_by_operator = $4
`

type SetPhotobookHiddenByOperatorParams struct {
	ID                 pgtype.UUID
	HiddenByOperator   bool
	UpdatedAt          pgtype.Timestamptz
	HiddenByOperator_2 bool
}

// PR34b: 運営による hide / unhide 操作。
// 計画書 §5.6 / ユーザー判断 #5 で version は上げない方針。published のみ対象。
// 0 行更新は呼び出し側で「対象が published でない or 既に目的状態」として扱う。
func (q *Queries) SetPhotobookHiddenByOperator(ctx context.Context, arg SetPhotobookHiddenByOperatorParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPhotobookHiddenByOperator,
		arg.ID,
		arg.HiddenByOperator,
		arg.UpdatedAt,
		arg.HiddenByOperator_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchDraftPhotobook = `-- name: TouchDraftPhotobook :execrows
UPDATE photobooks
   SET draft_expires_at = $2,
       updated_at       = now(),
       version          = version + 1
 WHERE id      = $1
   AND status  = 'draft'
   AND version = $3
`

type TouchDraftPhotobookParams struct {
	ID             pgtype.UUID
	DraftExpiresAt pgtype.Timestamptz
	Version        int32
}

func (q *Queries) TouchDraftPhotobook(ctx context.Context, arg TouchDraftPhotobookParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchDraftPhotobook, arg.ID, arg.DraftExpiresAt, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePhotobookSensitiveFromManage = `-- name: UpdatePhotobookSensitiveFromManage :execrows
UPDATE photobooks
   SET sensitive  = $2,
       updated_at = $3,
       version    = version + 1
 WHERE id      = $1
   AND status  = 'published'
   AND version = $4
`

type UpdatePhotobookSensitiveFromManageParams struct {
	ID        pgtype.UUID
	Sensitive bool
	UpdatedAt pgtype.Timestamptz
	Version   int32
}

// M-1a: sensitive flag を published photobook に対して更新する。
//
// /api/manage/photobooks/{id}/sensitive 経路から呼ぶ。`status='published'` 必須。
// 0 行影響は ErrOptimisticLockConflict。
func (q *Queries) UpdatePhotobookSensitiveFromManage(ctx context.Context, arg UpdatePhotobookSensitiveFromManageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePhotobookSensitiveFromManage,
		arg.ID,
		arg.Sensitive,
		arg.UpdatedAt,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePhotobookSettings = `-- name: UpdatePhotobookSettings :execrows
UPDATE photobooks
   SET type           = $2,
       title          = $3,
       description    = $4,
       layout         = $5,
       opening_style  = $6,
       visibility     = $7,
       cover_title    = $8,
       updated_at     = $9,
       version        = version + 1
 WHERE id      = $1
   AND status  = 'draft'
   AND version = $10
`

type UpdatePhotobookSettingsParams struct {
	ID           pgtype.UUID
	Type         string
	Title        string
	Description  *string
	Layout       string
	OpeningStyle string
	Visibility   string
	CoverTitle   *string
	UpdatedAt    pgtype.Timestamptz
	Version      int32
}

// UpdatePhotobookSettings: PR27 編集 UI から settings 一括 PATCH。
//
// title / description / type / layout / opening_style / visibility / cover_title を
// まとめて更新する。version+1 を含めて status='draft' AND version=$expected で OCC。
// 0 行影響は ErrOptimisticLockConflict。
func (q *Queries) UpdatePhotobookSettings(ctx context.Context, arg UpdatePhotobookSettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePhotobookSettings,
		arg.ID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Layout,
		arg.OpeningStyle,
		arg.Visibility,
		arg.CoverTitle,
		arg.UpdatedAt,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePhotobookVisibilityFromManage = `-- name: UpdatePhotobookVisibilityFromManage :execrows
UPDATE photobooks
   SET visibility = $2,
       updated_at = $3,
       version    = version + 1
 WHERE id      = $1
   AND status  = 'published'
   AND version = $4
`

type UpdatePhotobookVisibilityFromManageParams struct {
	ID         pgtype.UUID
	Visibility string
	UpdatedAt  pgtype.Timestamptz
	Version    int32
}

// M-1a: visibility を published photobook に対して更新する。
//
// /api/manage/photobooks/{id}/visibility 経路から呼ぶ。`status='published'` 必須、
// `unlisted` / `private` のみ受理（public は handler 側で reject、本 query は受理に来ない）。
// 0 行影響は ErrOptimisticLockConflict（version 不一致 / status≠published を区別しない）。
func (q *Queries) UpdatePhotobookVisibilityFromManage(ctx context.Context, arg UpdatePhotobookVisibilityFromManageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePhotobookVisibilityFromManage,
		arg.ID,
		arg.Visibility,
		arg.UpdatedAt,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
