// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photobook.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDraftPhotobook = `-- name: CreateDraftPhotobook :exec

INSERT INTO photobooks (
    id,
    type,
    title,
    description,
    layout,
    opening_style,
    visibility,
    sensitive,
    rights_agreed,
    rights_agreed_at,
    creator_display_name,
    creator_x_id,
    cover_title,
    cover_image_id,
    public_url_slug,
    manage_url_token_hash,
    manage_url_token_version,
    draft_edit_token_hash,
    draft_expires_at,
    status,
    hidden_by_operator,
    version,
    published_at,
    created_at,
    updated_at,
    deleted_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, NULL, NULL, $15, $16, $17,
    'draft', false, $18, NULL, $19, $20, NULL
)
`

type CreateDraftPhotobookParams struct {
	ID                    pgtype.UUID
	Type                  string
	Title                 string
	Description           *string
	Layout                string
	OpeningStyle          string
	Visibility            string
	Sensitive             bool
	RightsAgreed          bool
	RightsAgreedAt        pgtype.Timestamptz
	CreatorDisplayName    string
	CreatorXID            *string
	CoverTitle            *string
	CoverImageID          pgtype.UUID
	ManageUrlTokenVersion int32
	DraftEditTokenHash    []byte
	DraftExpiresAt        pgtype.Timestamptz
	Version               int32
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

// PR9a: Photobook 集約の sqlc query 群。
//
// 設計参照:
//   - docs/design/aggregates/photobook/データモデル設計.md
//   - docs/plan/m2-photobook-session-integration-plan.md §8
//
// セキュリティ:
//   - すべての UPDATE は version = $expectedVersion を WHERE に含める（楽観ロック）
//   - 0 行 UPDATE はアプリ層で OptimisticLockConflict として扱う
//   - draft 検索は draft_expires_at > now() を条件に含め、期限切れを抜け出させない
func (q *Queries) CreateDraftPhotobook(ctx context.Context, arg CreateDraftPhotobookParams) error {
	_, err := q.db.Exec(ctx, createDraftPhotobook,
		arg.ID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Layout,
		arg.OpeningStyle,
		arg.Visibility,
		arg.Sensitive,
		arg.RightsAgreed,
		arg.RightsAgreedAt,
		arg.CreatorDisplayName,
		arg.CreatorXID,
		arg.CoverTitle,
		arg.CoverImageID,
		arg.ManageUrlTokenVersion,
		arg.DraftEditTokenHash,
		arg.DraftExpiresAt,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const findPhotobookByDraftEditTokenHash = `-- name: FindPhotobookByDraftEditTokenHash :one
SELECT
    id, type, title, description, layout, opening_style, visibility,
    sensitive, rights_agreed, rights_agreed_at, creator_display_name,
    creator_x_id, cover_title, cover_image_id, public_url_slug,
    manage_url_token_hash, manage_url_token_version, draft_edit_token_hash,
    draft_expires_at, status, hidden_by_operator, version, published_at,
    created_at, updated_at, deleted_at
FROM photobooks
WHERE draft_edit_token_hash = $1
  AND status = 'draft'
  AND draft_expires_at > now()
`

func (q *Queries) FindPhotobookByDraftEditTokenHash(ctx context.Context, draftEditTokenHash []byte) (Photobook, error) {
	row := q.db.QueryRow(ctx, findPhotobookByDraftEditTokenHash, draftEditTokenHash)
	var i Photobook
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Layout,
		&i.OpeningStyle,
		&i.Visibility,
		&i.Sensitive,
		&i.RightsAgreed,
		&i.RightsAgreedAt,
		&i.CreatorDisplayName,
		&i.CreatorXID,
		&i.CoverTitle,
		&i.CoverImageID,
		&i.PublicUrlSlug,
		&i.ManageUrlTokenHash,
		&i.ManageUrlTokenVersion,
		&i.DraftEditTokenHash,
		&i.DraftExpiresAt,
		&i.Status,
		&i.HiddenByOperator,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findPhotobookByID = `-- name: FindPhotobookByID :one
SELECT
    id, type, title, description, layout, opening_style, visibility,
    sensitive, rights_agreed, rights_agreed_at, creator_display_name,
    creator_x_id, cover_title, cover_image_id, public_url_slug,
    manage_url_token_hash, manage_url_token_version, draft_edit_token_hash,
    draft_expires_at, status, hidden_by_operator, version, published_at,
    created_at, updated_at, deleted_at
FROM photobooks
WHERE id = $1
`

func (q *Queries) FindPhotobookByID(ctx context.Context, id pgtype.UUID) (Photobook, error) {
	row := q.db.QueryRow(ctx, findPhotobookByID, id)
	var i Photobook
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Layout,
		&i.OpeningStyle,
		&i.Visibility,
		&i.Sensitive,
		&i.RightsAgreed,
		&i.RightsAgreedAt,
		&i.CreatorDisplayName,
		&i.CreatorXID,
		&i.CoverTitle,
		&i.CoverImageID,
		&i.PublicUrlSlug,
		&i.ManageUrlTokenHash,
		&i.ManageUrlTokenVersion,
		&i.DraftEditTokenHash,
		&i.DraftExpiresAt,
		&i.Status,
		&i.HiddenByOperator,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findPhotobookByManageUrlTokenHash = `-- name: FindPhotobookByManageUrlTokenHash :one
SELECT
    id, type, title, description, layout, opening_style, visibility,
    sensitive, rights_agreed, rights_agreed_at, creator_display_name,
    creator_x_id, cover_title, cover_image_id, public_url_slug,
    manage_url_token_hash, manage_url_token_version, draft_edit_token_hash,
    draft_expires_at, status, hidden_by_operator, version, published_at,
    created_at, updated_at, deleted_at
FROM photobooks
WHERE manage_url_token_hash = $1
  AND status IN ('published', 'deleted')
`

func (q *Queries) FindPhotobookByManageUrlTokenHash(ctx context.Context, manageUrlTokenHash []byte) (Photobook, error) {
	row := q.db.QueryRow(ctx, findPhotobookByManageUrlTokenHash, manageUrlTokenHash)
	var i Photobook
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Layout,
		&i.OpeningStyle,
		&i.Visibility,
		&i.Sensitive,
		&i.RightsAgreed,
		&i.RightsAgreedAt,
		&i.CreatorDisplayName,
		&i.CreatorXID,
		&i.CoverTitle,
		&i.CoverImageID,
		&i.PublicUrlSlug,
		&i.ManageUrlTokenHash,
		&i.ManageUrlTokenVersion,
		&i.DraftEditTokenHash,
		&i.DraftExpiresAt,
		&i.Status,
		&i.HiddenByOperator,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findPhotobookBySlug = `-- name: FindPhotobookBySlug :one
SELECT
    id, type, title, description, layout, opening_style, visibility,
    sensitive, rights_agreed, rights_agreed_at, creator_display_name,
    creator_x_id, cover_title, cover_image_id, public_url_slug,
    manage_url_token_hash, manage_url_token_version, draft_edit_token_hash,
    draft_expires_at, status, hidden_by_operator, version, published_at,
    created_at, updated_at, deleted_at
FROM photobooks
WHERE public_url_slug = $1
  AND status = 'published'
  AND hidden_by_operator = false
`

func (q *Queries) FindPhotobookBySlug(ctx context.Context, publicUrlSlug *string) (Photobook, error) {
	row := q.db.QueryRow(ctx, findPhotobookBySlug, publicUrlSlug)
	var i Photobook
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Layout,
		&i.OpeningStyle,
		&i.Visibility,
		&i.Sensitive,
		&i.RightsAgreed,
		&i.RightsAgreedAt,
		&i.CreatorDisplayName,
		&i.CreatorXID,
		&i.CoverTitle,
		&i.CoverImageID,
		&i.PublicUrlSlug,
		&i.ManageUrlTokenHash,
		&i.ManageUrlTokenVersion,
		&i.DraftEditTokenHash,
		&i.DraftExpiresAt,
		&i.Status,
		&i.HiddenByOperator,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findPhotobookBySlugAny = `-- name: FindPhotobookBySlugAny :one
SELECT
    id, type, title, description, layout, opening_style, visibility,
    sensitive, rights_agreed, rights_agreed_at, creator_display_name,
    creator_x_id, cover_title, cover_image_id, public_url_slug,
    manage_url_token_hash, manage_url_token_version, draft_edit_token_hash,
    draft_expires_at, status, hidden_by_operator, version, published_at,
    created_at, updated_at, deleted_at
FROM photobooks
WHERE public_url_slug = $1
`

// FindPhotobookBySlugAny: slug 一致のみで status / hidden_by_operator を判別しない。
// PR25a 公開 Viewer は status / hidden / visibility を usecase 側で判定して
// 200 / 410 / 404 を分岐するため、より permissive な query を別に置く。
func (q *Queries) FindPhotobookBySlugAny(ctx context.Context, publicUrlSlug *string) (Photobook, error) {
	row := q.db.QueryRow(ctx, findPhotobookBySlugAny, publicUrlSlug)
	var i Photobook
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Layout,
		&i.OpeningStyle,
		&i.Visibility,
		&i.Sensitive,
		&i.RightsAgreed,
		&i.RightsAgreedAt,
		&i.CreatorDisplayName,
		&i.CreatorXID,
		&i.CoverTitle,
		&i.CoverImageID,
		&i.PublicUrlSlug,
		&i.ManageUrlTokenHash,
		&i.ManageUrlTokenVersion,
		&i.DraftEditTokenHash,
		&i.DraftExpiresAt,
		&i.Status,
		&i.HiddenByOperator,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const publishPhotobookFromDraft = `-- name: PublishPhotobookFromDraft :execrows
UPDATE photobooks
   SET status                   = 'published',
       public_url_slug          = $2,
       manage_url_token_hash    = $3,
       manage_url_token_version = 0,
       draft_edit_token_hash    = NULL,
       draft_expires_at         = NULL,
       published_at             = $4,
       updated_at               = $4,
       version                  = version + 1
 WHERE id      = $1
   AND status  = 'draft'
   AND version = $5
`

type PublishPhotobookFromDraftParams struct {
	ID                 pgtype.UUID
	PublicUrlSlug      *string
	ManageUrlTokenHash []byte
	PublishedAt        pgtype.Timestamptz
	Version            int32
}

func (q *Queries) PublishPhotobookFromDraft(ctx context.Context, arg PublishPhotobookFromDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, publishPhotobookFromDraft,
		arg.ID,
		arg.PublicUrlSlug,
		arg.ManageUrlTokenHash,
		arg.PublishedAt,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reissuePhotobookManageUrl = `-- name: ReissuePhotobookManageUrl :execrows
UPDATE photobooks
   SET manage_url_token_hash    = $2,
       manage_url_token_version = manage_url_token_version + 1,
       updated_at               = now(),
       version                  = version + 1
 WHERE id      = $1
   AND status  IN ('published', 'deleted')
   AND version = $3
`

type ReissuePhotobookManageUrlParams struct {
	ID                 pgtype.UUID
	ManageUrlTokenHash []byte
	Version            int32
}

func (q *Queries) ReissuePhotobookManageUrl(ctx context.Context, arg ReissuePhotobookManageUrlParams) (int64, error) {
	result, err := q.db.Exec(ctx, reissuePhotobookManageUrl, arg.ID, arg.ManageUrlTokenHash, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchDraftPhotobook = `-- name: TouchDraftPhotobook :execrows
UPDATE photobooks
   SET draft_expires_at = $2,
       updated_at       = now(),
       version          = version + 1
 WHERE id      = $1
   AND status  = 'draft'
   AND version = $3
`

type TouchDraftPhotobookParams struct {
	ID             pgtype.UUID
	DraftExpiresAt pgtype.Timestamptz
	Version        int32
}

func (q *Queries) TouchDraftPhotobook(ctx context.Context, arg TouchDraftPhotobookParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchDraftPhotobook, arg.ID, arg.DraftExpiresAt, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
