// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moderation.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createModerationAction = `-- name: CreateModerationAction :exec

INSERT INTO moderation_actions (
    id,
    kind,
    target_photobook_id,
    source_report_id,
    actor_label,
    reason,
    detail,
    correlation_id,
    executed_at,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $9
)
`

type CreateModerationActionParams struct {
	ID                pgtype.UUID
	Kind              string
	TargetPhotobookID pgtype.UUID
	SourceReportID    pgtype.UUID
	ActorLabel        string
	Reason            string
	Detail            *string
	CorrelationID     pgtype.UUID
	ExecutedAt        pgtype.Timestamptz
}

// PR34b: Moderation Action 集約の sqlc query。
//
// 設計参照:
//   - docs/design/aggregates/moderation/データモデル設計.md §3 / §5 / §8
//   - docs/plan/m2-moderation-ops-plan.md §5
//
// セキュリティ:
//   - detail に個人情報を書かない運用ガイド（runbook）。
//     Repository は単純に書き込むだけで sanitize しない（書き手側の責務）。
//   - actor_label は VO 側で正規表現バリデーション済（個人情報を含めない設計）。
//
// 重要:
//   - moderation_actions は **append-only**。本 file に UPDATE / DELETE は書かない。
//
// 同一 TX 内（hide/unhide UseCase 経由）で photobooks UPDATE と outbox_events INSERT
// と一緒に呼び出される前提。
func (q *Queries) CreateModerationAction(ctx context.Context, arg CreateModerationActionParams) error {
	_, err := q.db.Exec(ctx, createModerationAction,
		arg.ID,
		arg.Kind,
		arg.TargetPhotobookID,
		arg.SourceReportID,
		arg.ActorLabel,
		arg.Reason,
		arg.Detail,
		arg.CorrelationID,
		arg.ExecutedAt,
	)
	return err
}

const listModerationActionsByPhotobook = `-- name: ListModerationActionsByPhotobook :many
SELECT
    id,
    kind,
    target_photobook_id,
    source_report_id,
    actor_label,
    reason,
    detail,
    correlation_id,
    executed_at,
    created_at
FROM moderation_actions
WHERE target_photobook_id = $1
ORDER BY executed_at DESC
LIMIT $2
`

type ListModerationActionsByPhotobookParams struct {
	TargetPhotobookID pgtype.UUID
	Limit             int32
}

// 特定 photobook の操作履歴（最新順）。GetPhotobookForOps の直近 ≤ N 件取得に使う。
// INDEX moderation_actions_target_executed_idx を使う。
func (q *Queries) ListModerationActionsByPhotobook(ctx context.Context, arg ListModerationActionsByPhotobookParams) ([]ModerationAction, error) {
	rows, err := q.db.Query(ctx, listModerationActionsByPhotobook, arg.TargetPhotobookID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModerationAction
	for rows.Next() {
		var i ModerationAction
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.TargetPhotobookID,
			&i.SourceReportID,
			&i.ActorLabel,
			&i.Reason,
			&i.Detail,
			&i.CorrelationID,
			&i.ExecutedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
