// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HealthCheck struct {
	ID        int32
	CheckedAt pgtype.Timestamptz
}

type ModerationAction struct {
	ID                pgtype.UUID
	Kind              string
	TargetPhotobookID pgtype.UUID
	SourceReportID    pgtype.UUID
	ActorLabel        string
	Reason            string
	Detail            *string
	CorrelationID     pgtype.UUID
	ExecutedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}
