// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImage = `-- name: CreateImage :exec

INSERT INTO images (
    id,
    owner_photobook_id,
    usage_kind,
    source_format,
    status,
    uploaded_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, 'uploading', $5, $6, $7
)
`

type CreateImageParams struct {
	ID               pgtype.UUID
	OwnerPhotobookID pgtype.UUID
	UsageKind        string
	SourceFormat     string
	UploadedAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

// PR18: Image 集約の sqlc query 群。
//
// 設計参照:
//   - docs/design/aggregates/image/データモデル設計.md
//   - docs/plan/m2-image-upload-plan.md §4
//
// セキュリティ:
//   - storage_key / failure_reason などのログ出力には security-guard.md に従う
//   - 削除済 (deleted_at IS NOT NULL) を含めるかどうかは呼び出し側の責任
func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) error {
	_, err := q.db.Exec(ctx, createImage,
		arg.ID,
		arg.OwnerPhotobookID,
		arg.UsageKind,
		arg.SourceFormat,
		arg.UploadedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createImageVariant = `-- name: CreateImageVariant :exec
INSERT INTO image_variants (
    id,
    image_id,
    kind,
    storage_key,
    width,
    height,
    byte_size,
    mime_type,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type CreateImageVariantParams struct {
	ID         pgtype.UUID
	ImageID    pgtype.UUID
	Kind       string
	StorageKey string
	Width      int32
	Height     int32
	ByteSize   int64
	MimeType   string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateImageVariant(ctx context.Context, arg CreateImageVariantParams) error {
	_, err := q.db.Exec(ctx, createImageVariant,
		arg.ID,
		arg.ImageID,
		arg.Kind,
		arg.StorageKey,
		arg.Width,
		arg.Height,
		arg.ByteSize,
		arg.MimeType,
		arg.CreatedAt,
	)
	return err
}

const findImageByID = `-- name: FindImageByID :one
SELECT
    id, owner_photobook_id, usage_kind, source_format,
    normalized_format, original_width, original_height,
    original_byte_size, metadata_stripped_at,
    status, uploaded_at, available_at, failed_at,
    failure_reason, deleted_at, created_at, updated_at
FROM images
WHERE id = $1
`

func (q *Queries) FindImageByID(ctx context.Context, id pgtype.UUID) (Image, error) {
	row := q.db.QueryRow(ctx, findImageByID, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.OwnerPhotobookID,
		&i.UsageKind,
		&i.SourceFormat,
		&i.NormalizedFormat,
		&i.OriginalWidth,
		&i.OriginalHeight,
		&i.OriginalByteSize,
		&i.MetadataStrippedAt,
		&i.Status,
		&i.UploadedAt,
		&i.AvailableAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveImagesByPhotobookID = `-- name: ListActiveImagesByPhotobookID :many
SELECT
    id, owner_photobook_id, usage_kind, source_format,
    normalized_format, original_width, original_height,
    original_byte_size, metadata_stripped_at,
    status, uploaded_at, available_at, failed_at,
    failure_reason, deleted_at, created_at, updated_at
FROM images
WHERE owner_photobook_id = $1
  AND deleted_at IS NULL
ORDER BY uploaded_at ASC
`

func (q *Queries) ListActiveImagesByPhotobookID(ctx context.Context, ownerPhotobookID pgtype.UUID) ([]Image, error) {
	rows, err := q.db.Query(ctx, listActiveImagesByPhotobookID, ownerPhotobookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.OwnerPhotobookID,
			&i.UsageKind,
			&i.SourceFormat,
			&i.NormalizedFormat,
			&i.OriginalWidth,
			&i.OriginalHeight,
			&i.OriginalByteSize,
			&i.MetadataStrippedAt,
			&i.Status,
			&i.UploadedAt,
			&i.AvailableAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImageVariantsByImageID = `-- name: ListImageVariantsByImageID :many
SELECT
    id, image_id, kind, storage_key,
    width, height, byte_size, mime_type, created_at
FROM image_variants
WHERE image_id = $1
ORDER BY kind ASC
`

func (q *Queries) ListImageVariantsByImageID(ctx context.Context, imageID pgtype.UUID) ([]ImageVariant, error) {
	rows, err := q.db.Query(ctx, listImageVariantsByImageID, imageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImageVariant
	for rows.Next() {
		var i ImageVariant
		if err := rows.Scan(
			&i.ID,
			&i.ImageID,
			&i.Kind,
			&i.StorageKey,
			&i.Width,
			&i.Height,
			&i.ByteSize,
			&i.MimeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcessingImagesForUpdate = `-- name: ListProcessingImagesForUpdate :many
SELECT
    id, owner_photobook_id, usage_kind, source_format,
    normalized_format, original_width, original_height,
    original_byte_size, metadata_stripped_at,
    status, uploaded_at, available_at, failed_at,
    failure_reason, deleted_at, created_at, updated_at
FROM images
WHERE status = 'processing'
  AND deleted_at IS NULL
ORDER BY uploaded_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// ListProcessingImagesForUpdate
//
// M2 image-processor: status='processing' の Image を最大 N 件 claim する。
//
// FOR UPDATE SKIP LOCKED により、複数 worker が並列で動いても同じ row を二重 claim しない。
// 呼び出し側は短い TX 内で claim → return → 別 TX で重い処理（GetObject / 画像処理 / PUT）
// → 別 TX で finalize（MarkAvailable / MarkFailed）するパターンを取る。
//
// 並び順は uploaded_at ASC（古い順、stuck 検出時に最も困る順）。
func (q *Queries) ListProcessingImagesForUpdate(ctx context.Context, limit int32) ([]Image, error) {
	rows, err := q.db.Query(ctx, listProcessingImagesForUpdate, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.OwnerPhotobookID,
			&i.UsageKind,
			&i.SourceFormat,
			&i.NormalizedFormat,
			&i.OriginalWidth,
			&i.OriginalHeight,
			&i.OriginalByteSize,
			&i.MetadataStrippedAt,
			&i.Status,
			&i.UploadedAt,
			&i.AvailableAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markImageDeleted = `-- name: MarkImageDeleted :execrows
UPDATE images
   SET status     = 'deleted',
       deleted_at = $2,
       updated_at = $3
 WHERE id     = $1
   AND status IN ('available', 'failed')
`

type MarkImageDeletedParams struct {
	ID        pgtype.UUID
	DeletedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) MarkImageDeleted(ctx context.Context, arg MarkImageDeletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markImageDeleted, arg.ID, arg.DeletedAt, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateImageStatusAvailable = `-- name: UpdateImageStatusAvailable :execrows
UPDATE images
   SET status               = 'available',
       normalized_format    = $2,
       original_width       = $3,
       original_height      = $4,
       original_byte_size   = $5,
       metadata_stripped_at = $6,
       available_at         = $7,
       updated_at           = $8
 WHERE id     = $1
   AND status = 'processing'
`

type UpdateImageStatusAvailableParams struct {
	ID                 pgtype.UUID
	NormalizedFormat   *string
	OriginalWidth      *int32
	OriginalHeight     *int32
	OriginalByteSize   *int64
	MetadataStrippedAt pgtype.Timestamptz
	AvailableAt        pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) UpdateImageStatusAvailable(ctx context.Context, arg UpdateImageStatusAvailableParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateImageStatusAvailable,
		arg.ID,
		arg.NormalizedFormat,
		arg.OriginalWidth,
		arg.OriginalHeight,
		arg.OriginalByteSize,
		arg.MetadataStrippedAt,
		arg.AvailableAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateImageStatusFailed = `-- name: UpdateImageStatusFailed :execrows
UPDATE images
   SET status         = 'failed',
       failure_reason = $2,
       failed_at      = $3,
       updated_at     = $4
 WHERE id     = $1
   AND status IN ('uploading', 'processing')
`

type UpdateImageStatusFailedParams struct {
	ID            pgtype.UUID
	FailureReason *string
	FailedAt      pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) UpdateImageStatusFailed(ctx context.Context, arg UpdateImageStatusFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateImageStatusFailed,
		arg.ID,
		arg.FailureReason,
		arg.FailedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateImageStatusProcessing = `-- name: UpdateImageStatusProcessing :execrows
UPDATE images
   SET status     = 'processing',
       updated_at = $2
 WHERE id = $1
   AND status = 'uploading'
`

type UpdateImageStatusProcessingParams struct {
	ID        pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateImageStatusProcessing(ctx context.Context, arg UpdateImageStatusProcessingParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateImageStatusProcessing, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
