// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TestAlive struct {
	ID        int64
	Note      string
	CreatedAt pgtype.Timestamptz
}

type UploadVerificationSession struct {
	ID                 pgtype.UUID
	SessionTokenHash   []byte
	PhotobookID        pgtype.UUID
	AllowedIntentCount int32
	UsedIntentCount    int32
	ExpiresAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	RevokedAt          pgtype.Timestamptz
}
