// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxEvent struct {
	ID            pgtype.UUID
	EventType     string
	AggregateType string
	AggregateID   pgtype.UUID
	Payload       []byte
	Status        string
	Attempts      int32
	NextAttemptAt pgtype.Timestamptz
	LastError     *string
	CreatedAt     pgtype.Timestamptz
	ProcessedAt   pgtype.Timestamptz
	LockedAt      pgtype.Timestamptz
}

type TestAlive struct {
	ID        int64
	Note      string
	CreatedAt pgtype.Timestamptz
}

type UploadVerificationSession struct {
	ID                 pgtype.UUID
	SessionTokenHash   []byte
	PhotobookID        pgtype.UUID
	AllowedIntentCount int32
	UsedIntentCount    int32
	ExpiresAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	RevokedAt          pgtype.Timestamptz
}
