// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TestAlive struct {
	ID        int64
	Note      string
	CreatedAt pgtype.Timestamptz
}
