// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingOutboxEvents = `-- name: ClaimPendingOutboxEvents :many
WITH claimed AS (
    SELECT id
    FROM outbox_events
    WHERE status = 'pending'
      AND next_attempt_at <= now()
    ORDER BY next_attempt_at, created_at
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
UPDATE outbox_events o
SET status     = 'processing',
    attempts   = attempts + 1,
    locked_at  = now()
FROM claimed
WHERE o.id = claimed.id
RETURNING o.id, o.event_type, o.aggregate_type, o.aggregate_id,
          o.payload, o.attempts, o.created_at
`

type ClaimPendingOutboxEventsRow struct {
	ID            pgtype.UUID
	EventType     string
	AggregateType string
	AggregateID   pgtype.UUID
	Payload       []byte
	Attempts      int32
	CreatedAt     pgtype.Timestamptz
}

// pending かつ next_attempt_at 到達済のイベントを最大 $1 件取得して
// アトミックに status='processing' に遷移する。
// FOR UPDATE SKIP LOCKED によって複数ワーカーが同じ行を取得しない。
func (q *Queries) ClaimPendingOutboxEvents(ctx context.Context, limit int32) ([]ClaimPendingOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, claimPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimPendingOutboxEventsRow
	for rows.Next() {
		var i ClaimPendingOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOutboxEventsByStatus = `-- name: CountOutboxEventsByStatus :many
SELECT status, COUNT(*) AS count
FROM outbox_events
GROUP BY status
ORDER BY status
`

type CountOutboxEventsByStatusRow struct {
	Status string
	Count  int64
}

// 検証用の status 別集計。一覧と組み合わせて使う。
func (q *Queries) CountOutboxEventsByStatus(ctx context.Context) ([]CountOutboxEventsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countOutboxEventsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountOutboxEventsByStatusRow
	for rows.Next() {
		var i CountOutboxEventsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOutboxEvent = `-- name: CreateOutboxEvent :one

INSERT INTO outbox_events (
    id,
    event_type,
    aggregate_type,
    aggregate_id,
    payload,
    status,
    attempts,
    next_attempt_at
) VALUES (
    $1, $2, $3, $4, $5, 'pending', 0, now()
)
RETURNING id, event_type, aggregate_type, aggregate_id, status,
          attempts, next_attempt_at, created_at
`

type CreateOutboxEventParams struct {
	ID            pgtype.UUID
	EventType     string
	AggregateType string
	AggregateID   pgtype.UUID
	Payload       []byte
}

type CreateOutboxEventRow struct {
	ID            pgtype.UUID
	EventType     string
	AggregateType string
	AggregateID   pgtype.UUID
	Status        string
	Attempts      int32
	NextAttemptAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

// M1 spike: outbox_events の最小 sqlc クエリ。
// 本実装では outbox 横断モジュールの Repository として再整備する。
// 集約の状態変更と同一 TX で呼び出す前提（PoC では sandbox 経由で単独 INSERT）。
func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (CreateOutboxEventRow, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.ID,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.Payload,
	)
	var i CreateOutboxEventRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.CreatedAt,
	)
	return i, err
}

const listOutboxEvents = `-- name: ListOutboxEvents :many
SELECT id, event_type, aggregate_type, aggregate_id, status,
       attempts, created_at, processed_at
FROM outbox_events
ORDER BY created_at DESC
LIMIT $1
`

type ListOutboxEventsRow struct {
	ID            pgtype.UUID
	EventType     string
	AggregateType string
	AggregateID   pgtype.UUID
	Status        string
	Attempts      int32
	CreatedAt     pgtype.Timestamptz
	ProcessedAt   pgtype.Timestamptz
}

// 検証用の最小一覧。payload / last_error はクライアントへ返さない（情報量を絞る）。
func (q *Queries) ListOutboxEvents(ctx context.Context, limit int32) ([]ListOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, listOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutboxEventsRow
	for rows.Next() {
		var i ListOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE outbox_events
SET status     = 'failed',
    last_error = $2,
    locked_at  = NULL
WHERE id = $1
  AND status = 'processing'
`

type MarkOutboxFailedParams struct {
	ID        pgtype.UUID
	LastError *string
}

// ハンドラ失敗時、status='failed' に遷移する（PoC では指数バックオフを導入せず
// ターミナル failed に集約。本実装では attempts に応じて pending 戻し or failed を選ぶ）。
func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxFailed, arg.ID, arg.LastError)
	return err
}

const markOutboxProcessed = `-- name: MarkOutboxProcessed :exec
UPDATE outbox_events
SET status       = 'processed',
    processed_at = now(),
    last_error   = NULL,
    locked_at    = NULL
WHERE id = $1
  AND status = 'processing'
`

// ハンドラ成功時、processed に遷移する。
func (q *Queries) MarkOutboxProcessed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxProcessed, id)
	return err
}

const resetOutboxForTest = `-- name: ResetOutboxForTest :exec
DELETE FROM outbox_events
`

// PoC 検証用: outbox_events を全件削除する。
// 本実装には流用しない（運用 API は outbox_failed.sh などの reconcile を使う）。
func (q *Queries) ResetOutboxForTest(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetOutboxForTest)
	return err
}

const retryFailedOutboxEvents = `-- name: RetryFailedOutboxEvents :execrows
UPDATE outbox_events
SET status          = 'pending',
    next_attempt_at = now(),
    locked_at       = NULL
WHERE status = 'failed'
`

// 自動 reconciler `outbox_failed_retry` の最小実装（cross-cutting/reconcile-scripts.md §3.7.2）。
// failed 状態のイベントを pending に戻し、再度 worker が拾えるようにする。
// 戻り値は影響行数（再投入したイベント数）。
func (q *Queries) RetryFailedOutboxEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, retryFailedOutboxEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
