// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: test_alive.sql

package sqlcgen

import (
	"context"
)

const getLatestAlive = `-- name: GetLatestAlive :one

SELECT id, note, created_at
FROM _test_alive
ORDER BY id DESC
LIMIT 1
`

// M1 spike: sqlc 生成元クエリの最小サンプル。本実装では使わない。
func (q *Queries) GetLatestAlive(ctx context.Context) (TestAlive, error) {
	row := q.db.QueryRow(ctx, getLatestAlive)
	var i TestAlive
	err := row.Scan(&i.ID, &i.Note, &i.CreatedAt)
	return i, err
}

const insertAlive = `-- name: InsertAlive :one
INSERT INTO _test_alive (note)
VALUES ($1)
RETURNING id, note, created_at
`

func (q *Queries) InsertAlive(ctx context.Context, note string) (TestAlive, error) {
	row := q.db.QueryRow(ctx, insertAlive, note)
	var i TestAlive
	err := row.Scan(&i.ID, &i.Note, &i.CreatedAt)
	return i, err
}
