// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upload_verification.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeUploadVerificationIntent = `-- name: ConsumeUploadVerificationIntent :one
UPDATE upload_verification_sessions
SET used_intent_count = used_intent_count + 1
WHERE session_token_hash = $1
  AND photobook_id = $2
  AND revoked_at IS NULL
  AND expires_at > now()
  AND used_intent_count < allowed_intent_count
RETURNING used_intent_count, allowed_intent_count
`

type ConsumeUploadVerificationIntentParams struct {
	SessionTokenHash []byte
	PhotobookID      pgtype.UUID
}

type ConsumeUploadVerificationIntentRow struct {
	UsedIntentCount    int32
	AllowedIntentCount int32
}

// アトミック消費: hash 一致 + photobook_id 一致 + 有効期限 + revoked なし + 残数あり
// すべてを満たすときのみ used_intent_count を +1 し、その後の値を返す。
// 0 行返却（pgx.ErrNoRows）のとき呼び出し側で「拒否（exhausted/expired/revoked/not_found のいずれか）」と判定する。
func (q *Queries) ConsumeUploadVerificationIntent(ctx context.Context, arg ConsumeUploadVerificationIntentParams) (ConsumeUploadVerificationIntentRow, error) {
	row := q.db.QueryRow(ctx, consumeUploadVerificationIntent, arg.SessionTokenHash, arg.PhotobookID)
	var i ConsumeUploadVerificationIntentRow
	err := row.Scan(&i.UsedIntentCount, &i.AllowedIntentCount)
	return i, err
}

const createUploadVerificationSession = `-- name: CreateUploadVerificationSession :one

INSERT INTO upload_verification_sessions (
    id,
    session_token_hash,
    photobook_id,
    allowed_intent_count,
    used_intent_count,
    expires_at
) VALUES (
    $1, $2, $3, $4, 0, $5
)
RETURNING id, photobook_id, allowed_intent_count, used_intent_count,
          expires_at, created_at, revoked_at
`

type CreateUploadVerificationSessionParams struct {
	ID                 pgtype.UUID
	SessionTokenHash   []byte
	PhotobookID        pgtype.UUID
	AllowedIntentCount int32
	ExpiresAt          pgtype.Timestamptz
}

type CreateUploadVerificationSessionRow struct {
	ID                 pgtype.UUID
	PhotobookID        pgtype.UUID
	AllowedIntentCount int32
	UsedIntentCount    int32
	ExpiresAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	RevokedAt          pgtype.Timestamptz
}

// M1 spike: upload_verification_sessions の最小 sqlc クエリ。
// 本実装では auth/upload-verification 集約 Repository として整備する。
func (q *Queries) CreateUploadVerificationSession(ctx context.Context, arg CreateUploadVerificationSessionParams) (CreateUploadVerificationSessionRow, error) {
	row := q.db.QueryRow(ctx, createUploadVerificationSession,
		arg.ID,
		arg.SessionTokenHash,
		arg.PhotobookID,
		arg.AllowedIntentCount,
		arg.ExpiresAt,
	)
	var i CreateUploadVerificationSessionRow
	err := row.Scan(
		&i.ID,
		&i.PhotobookID,
		&i.AllowedIntentCount,
		&i.UsedIntentCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUploadVerificationSessionByHash = `-- name: GetUploadVerificationSessionByHash :one
SELECT id, session_token_hash, photobook_id, allowed_intent_count,
       used_intent_count, expires_at, created_at, revoked_at
FROM upload_verification_sessions
WHERE session_token_hash = $1
`

func (q *Queries) GetUploadVerificationSessionByHash(ctx context.Context, sessionTokenHash []byte) (UploadVerificationSession, error) {
	row := q.db.QueryRow(ctx, getUploadVerificationSessionByHash, sessionTokenHash)
	var i UploadVerificationSession
	err := row.Scan(
		&i.ID,
		&i.SessionTokenHash,
		&i.PhotobookID,
		&i.AllowedIntentCount,
		&i.UsedIntentCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
