// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HealthCheck struct {
	ID        int32
	CheckedAt pgtype.Timestamptz
}

type UsageCounter struct {
	ScopeType       string
	ScopeHash       string
	Action          string
	WindowStart     pgtype.Timestamptz
	WindowSeconds   int32
	Count           int32
	LimitAtCreation int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
}
