// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HealthCheck struct {
	ID        int32
	CheckedAt pgtype.Timestamptz
}

type Photobook struct {
	ID                    pgtype.UUID
	Type                  string
	Title                 string
	Description           *string
	Layout                string
	OpeningStyle          string
	Visibility            string
	Sensitive             bool
	RightsAgreed          bool
	RightsAgreedAt        pgtype.Timestamptz
	CreatorDisplayName    string
	CreatorXID            *string
	CoverTitle            *string
	CoverImageID          pgtype.UUID
	PublicUrlSlug         *string
	ManageUrlTokenHash    []byte
	ManageUrlTokenVersion int32
	DraftEditTokenHash    []byte
	DraftExpiresAt        pgtype.Timestamptz
	Status                string
	HiddenByOperator      bool
	Version               int32
	PublishedAt           pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
}

type UploadVerificationSession struct {
	ID                 pgtype.UUID
	PhotobookID        pgtype.UUID
	SessionTokenHash   []byte
	AllowedIntentCount int32
	UsedIntentCount    int32
	ExpiresAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	RevokedAt          pgtype.Timestamptz
}
