// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upload_verification.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeUploadVerificationSession = `-- name: ConsumeUploadVerificationSession :one
UPDATE upload_verification_sessions
   SET used_intent_count = used_intent_count + 1
 WHERE session_token_hash = $1
   AND photobook_id       = $2
   AND used_intent_count  < allowed_intent_count
   AND expires_at         > now()
   AND revoked_at         IS NULL
RETURNING id, used_intent_count, allowed_intent_count
`

type ConsumeUploadVerificationSessionParams struct {
	SessionTokenHash []byte
	PhotobookID      pgtype.UUID
}

type ConsumeUploadVerificationSessionRow struct {
	ID                 pgtype.UUID
	UsedIntentCount    int32
	AllowedIntentCount int32
}

// atomic consume: 単一 UPDATE で row-level lock を取り、
// used_intent_count < allowed_intent_count かつ未期限切れ・未 revoke のみ +1。
// 0 行影響は呼び出し側で ErrUploadVerificationFailed として扱う。
func (q *Queries) ConsumeUploadVerificationSession(ctx context.Context, arg ConsumeUploadVerificationSessionParams) (ConsumeUploadVerificationSessionRow, error) {
	row := q.db.QueryRow(ctx, consumeUploadVerificationSession, arg.SessionTokenHash, arg.PhotobookID)
	var i ConsumeUploadVerificationSessionRow
	err := row.Scan(&i.ID, &i.UsedIntentCount, &i.AllowedIntentCount)
	return i, err
}

const countActiveUploadVerificationSessionsByPhotobookID = `-- name: CountActiveUploadVerificationSessionsByPhotobookID :one
SELECT COUNT(*)::int AS cnt
FROM upload_verification_sessions
WHERE photobook_id = $1
  AND expires_at   > now()
  AND revoked_at   IS NULL
`

func (q *Queries) CountActiveUploadVerificationSessionsByPhotobookID(ctx context.Context, photobookID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveUploadVerificationSessionsByPhotobookID, photobookID)
	var cnt int32
	err := row.Scan(&cnt)
	return cnt, err
}

const createUploadVerificationSession = `-- name: CreateUploadVerificationSession :exec

INSERT INTO upload_verification_sessions (
    id,
    photobook_id,
    session_token_hash,
    allowed_intent_count,
    used_intent_count,
    expires_at,
    created_at
) VALUES (
    $1, $2, $3, $4, 0, $5, $6
)
`

type CreateUploadVerificationSessionParams struct {
	ID                 pgtype.UUID
	PhotobookID        pgtype.UUID
	SessionTokenHash   []byte
	AllowedIntentCount int32
	ExpiresAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
}

// PR20: Upload Verification Session の sqlc query 群。
//
// 設計参照:
//   - docs/adr/0005-image-upload-flow.md §upload_verification_session
//   - docs/plan/m2-upload-verification-plan.md §3 / §7
//
// セキュリティ:
//   - すべての consume は単一 UPDATE で atomic に実行（FOR UPDATE 不要）
//   - 0 行影響時の理由は外に漏らさない（ErrUploadVerificationFailed で一括）
func (q *Queries) CreateUploadVerificationSession(ctx context.Context, arg CreateUploadVerificationSessionParams) error {
	_, err := q.db.Exec(ctx, createUploadVerificationSession,
		arg.ID,
		arg.PhotobookID,
		arg.SessionTokenHash,
		arg.AllowedIntentCount,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const findUploadVerificationSessionByID = `-- name: FindUploadVerificationSessionByID :one
SELECT id, photobook_id, session_token_hash, allowed_intent_count,
       used_intent_count, expires_at, created_at, revoked_at
FROM upload_verification_sessions
WHERE id = $1
`

func (q *Queries) FindUploadVerificationSessionByID(ctx context.Context, id pgtype.UUID) (UploadVerificationSession, error) {
	row := q.db.QueryRow(ctx, findUploadVerificationSessionByID, id)
	var i UploadVerificationSession
	err := row.Scan(
		&i.ID,
		&i.PhotobookID,
		&i.SessionTokenHash,
		&i.AllowedIntentCount,
		&i.UsedIntentCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const findUploadVerificationSessionByTokenHash = `-- name: FindUploadVerificationSessionByTokenHash :one
SELECT id, photobook_id, session_token_hash, allowed_intent_count,
       used_intent_count, expires_at, created_at, revoked_at
FROM upload_verification_sessions
WHERE session_token_hash = $1
`

func (q *Queries) FindUploadVerificationSessionByTokenHash(ctx context.Context, sessionTokenHash []byte) (UploadVerificationSession, error) {
	row := q.db.QueryRow(ctx, findUploadVerificationSessionByTokenHash, sessionTokenHash)
	var i UploadVerificationSession
	err := row.Scan(
		&i.ID,
		&i.PhotobookID,
		&i.SessionTokenHash,
		&i.AllowedIntentCount,
		&i.UsedIntentCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeUploadVerificationSession = `-- name: RevokeUploadVerificationSession :execrows
UPDATE upload_verification_sessions
   SET revoked_at = $2
 WHERE id         = $1
   AND revoked_at IS NULL
`

type RevokeUploadVerificationSessionParams struct {
	ID        pgtype.UUID
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeUploadVerificationSession(ctx context.Context, arg RevokeUploadVerificationSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUploadVerificationSession, arg.ID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
